package io.appmetrica.analytics.impl

object CounterConfigurationKeys {

    private const val CFG_PREFIX = "CFG_"
    const val DISPATCH_PERIOD = CFG_PREFIX + "DISPATCH_PERIOD"
    const val SESSION_TIMEOUT = CFG_PREFIX + "SESSION_TIMEOUT"
    const val MAX_REPORTS_COUNT = CFG_PREFIX + "MAX_REPORTS_COUNT"
    const val LOCATION_TRACKING_ENABLED = CFG_PREFIX + "LOCATION_TRACKING"
    const val ADV_IDENTIFIERS_TRACKING_ENABLED = CFG_PREFIX + "ADV_IDENTIFIERS_TRACKING_ENABLED"
    const val ADV_IDENTIFIERS_TRACKING_ENABLED_FORCED = CFG_PREFIX + "ADV_IDENTIFIERS_TRACKING_ENABLED_FORCED"
    const val MANUAL_LOCATION = CFG_PREFIX + "MANUAL_LOCATION"
    const val APP_VERSION = CFG_PREFIX + "APP_VERSION"
    const val APP_BUILD_NUMBER = CFG_PREFIX + "APP_VERSION_CODE"
    const val API_KEY = CFG_PREFIX + "API_KEY"
    const val UUID = CFG_PREFIX + "UUID"
    const val DEVICE_ID = CFG_PREFIX + "DEVICE_ID"
    const val REPORTER_TYPE = CFG_PREFIX + "REPORTER_TYPE"
    const val DEVICE_SIZE_TYPE = CFG_PREFIX + "DEVICE_SIZE_TYPE"
    const val IS_LOG_ENABLED = CFG_PREFIX + "IS_LOG_ENABLED"
    const val IS_FIRST_ACTIVATION_AS_UPDATE = CFG_PREFIX + "IS_FIRST_ACTIVATION_AS_UPDATE"
    const val DATA_SENDING_ENABLED = CFG_PREFIX + "DATA_SENDING_ENABLED"
    const val MAX_REPORTS_IN_DB_COUNT = "MAX_REPORTS_IN_DB_COUNT"
    const val NATIVE_CRASHES_ENABLED = CFG_PREFIX + "NATIVE_CRASHES_ENABLED"
    const val REVENUE_AUTO_TRACKING_ENABLED = CFG_PREFIX + "REVENUE_AUTO_TRACKING_ENABLED"
    const val AUTO_COLLECTED_DATA_SUBSCRIBERS = CFG_PREFIX + "AUTO_COLLECTED_DATA_SUBSCRIBERS"

    // To put CounterConfiguration object to Bundle
    const val METRICA_CONFIG_EXTRA = "COUNTER_" + CFG_PREFIX + "OBJ"
}
