// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.appmetrica.analytics.adrevenue.other.impl.protobuf.client;

@SuppressWarnings("hiding")
public interface AdRevenueOtherConfigProtobuf {

  public static final class AdRevenueOtherConfig extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile AdRevenueOtherConfig[] _emptyArray;
    public static AdRevenueOtherConfig[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AdRevenueOtherConfig[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bool enabled = 1 [default = false];
    public boolean enabled;

    // optional bool includeSource = 2 [default = false];
    public boolean includeSource;

    public AdRevenueOtherConfig() {
      clear();
    }

    public AdRevenueOtherConfig clear() {
      enabled = false;
      includeSource = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.enabled != false) {
        output.writeBool(1, this.enabled);
      }
      if (this.includeSource != false) {
        output.writeBool(2, this.includeSource);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.enabled != false) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(1, this.enabled);
      }
      if (this.includeSource != false) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(2, this.includeSource);
      }
      return size;
    }

    @Override
    public AdRevenueOtherConfig mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.enabled = input.readBool();
            break;
          }
          case 16: {
            this.includeSource = input.readBool();
            break;
          }
        }
      }
    }

    public static AdRevenueOtherConfig parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new AdRevenueOtherConfig(), data);
    }

    public static AdRevenueOtherConfig parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AdRevenueOtherConfig().mergeFrom(input);
    }
  }
}
