// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.appmetrica.analytics.idsync.impl.protobuf.client;

@SuppressWarnings("hiding")
public interface IdSyncProtobuf {

  public static final class IdSyncConfig extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    // enum NetworkType
    public static final int NETWORK_TYPE_ANY = 0;
    public static final int NETWORK_TYPE_CELL = 1;

    public static final class Preconditions extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile Preconditions[] _emptyArray;
      public static Preconditions[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Preconditions[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional .IdSyncConfig.NetworkType network_type = 1 [default = NETWORK_TYPE_ANY];
      public int networkType;

      public Preconditions() {
        clear();
      }

      public Preconditions clear() {
        networkType = IdSyncProtobuf.IdSyncConfig.NETWORK_TYPE_ANY;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.networkType != IdSyncProtobuf.IdSyncConfig.NETWORK_TYPE_ANY) {
          output.writeInt32(1, this.networkType);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.networkType != IdSyncProtobuf.IdSyncConfig.NETWORK_TYPE_ANY) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.networkType);
        }
        return size;
      }

      @Override
      public Preconditions mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              int value = input.readInt32();
              switch (value) {
                case IdSyncProtobuf.IdSyncConfig.NETWORK_TYPE_ANY:
                case IdSyncProtobuf.IdSyncConfig.NETWORK_TYPE_CELL:
                  this.networkType = value;
                  break;
              }
              break;
            }
          }
        }
      }

      public static Preconditions parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Preconditions(), data);
      }

      public static Preconditions parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Preconditions().mergeFrom(input);
      }
    }

    public static final class Header extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile Header[] _emptyArray;
      public static Header[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Header[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional bytes name = 1;
      public byte[] name;

      // repeated bytes value = 2;
      public byte[][] value;

      public Header() {
        clear();
      }

      public Header clear() {
        name = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
        value = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES_ARRAY;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!java.util.Arrays.equals(this.name, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          output.writeBytes(1, this.name);
        }
        if (this.value != null && this.value.length > 0) {
          for (int i = 0; i < this.value.length; i++) {
            byte[] element = this.value[i];
            if (element != null) {
              output.writeBytes(2, element);
            }
          }
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!java.util.Arrays.equals(this.name, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBytesSize(1, this.name);
        }
        if (this.value != null && this.value.length > 0) {
          int dataCount = 0;
          int dataSize = 0;
          for (int i = 0; i < this.value.length; i++) {
            byte[] element = this.value[i];
            if (element != null) {
              dataCount++;
              dataSize += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
                  .computeBytesSizeNoTag(element);
            }
          }
          size += dataSize;
          size += 1 * dataCount;
        }
        return size;
      }

      @Override
      public Header mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.name = input.readBytes();
              break;
            }
            case 18: {
              int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 18);
              int i = this.value == null ? 0 : this.value.length;
              byte[][] newArray = new byte[i + arrayLength][];
              if (i != 0) {
                java.lang.System.arraycopy(this.value, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = input.readBytes();
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = input.readBytes();
              this.value = newArray;
              break;
            }
          }
        }
      }

      public static Header parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Header(), data);
      }

      public static Header parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Header().mergeFrom(input);
      }
    }

    public static final class Request extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile Request[] _emptyArray;
      public static Request[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Request[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional bytes type = 1;
      public byte[] type;

      // optional .IdSyncConfig.Preconditions preconditions = 2;
      public IdSyncProtobuf.IdSyncConfig.Preconditions preconditions;

      // optional bytes url = 3;
      public byte[] url;

      // repeated .IdSyncConfig.Header headers = 4;
      public IdSyncProtobuf.IdSyncConfig.Header[] headers;

      // optional uint64 resend_interval_for_valid_response = 5 [default = 86400000];
      public long resendIntervalForValidResponse;

      // optional uint64 resend_interval_for_invalid_response = 6 [default = 3600000];
      public long resendIntervalForInvalidResponse;

      // repeated uint32 valid_response_codes = 7;
      public int[] validResponseCodes;

      // optional bool report_event_enabled = 8 [default = true];
      public boolean reportEventEnabled;

      // optional string report_url = 9;
      public java.lang.String reportUrl;

      public Request() {
        clear();
      }

      public Request clear() {
        type = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
        preconditions = null;
        url = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
        headers = IdSyncProtobuf.IdSyncConfig.Header.emptyArray();
        resendIntervalForValidResponse = 86400000L;
        resendIntervalForInvalidResponse = 3600000L;
        validResponseCodes = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_INT_ARRAY;
        reportEventEnabled = true;
        reportUrl = "";
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!java.util.Arrays.equals(this.type, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          output.writeBytes(1, this.type);
        }
        if (this.preconditions != null) {
          output.writeMessage(2, this.preconditions);
        }
        if (!java.util.Arrays.equals(this.url, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          output.writeBytes(3, this.url);
        }
        if (this.headers != null && this.headers.length > 0) {
          for (int i = 0; i < this.headers.length; i++) {
            IdSyncProtobuf.IdSyncConfig.Header element = this.headers[i];
            if (element != null) {
              output.writeMessage(4, element);
            }
          }
        }
        if (this.resendIntervalForValidResponse != 86400000L) {
          output.writeUInt64(5, this.resendIntervalForValidResponse);
        }
        if (this.resendIntervalForInvalidResponse != 3600000L) {
          output.writeUInt64(6, this.resendIntervalForInvalidResponse);
        }
        if (this.validResponseCodes != null && this.validResponseCodes.length > 0) {
          for (int i = 0; i < this.validResponseCodes.length; i++) {
            output.writeUInt32(7, this.validResponseCodes[i]);
          }
        }
        if (this.reportEventEnabled != true) {
          output.writeBool(8, this.reportEventEnabled);
        }
        if (!this.reportUrl.equals("")) {
          output.writeString(9, this.reportUrl);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!java.util.Arrays.equals(this.type, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBytesSize(1, this.type);
        }
        if (this.preconditions != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(2, this.preconditions);
        }
        if (!java.util.Arrays.equals(this.url, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBytesSize(3, this.url);
        }
        if (this.headers != null && this.headers.length > 0) {
          for (int i = 0; i < this.headers.length; i++) {
            IdSyncProtobuf.IdSyncConfig.Header element = this.headers[i];
            if (element != null) {
              size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
                .computeMessageSize(4, element);
            }
          }
        }
        if (this.resendIntervalForValidResponse != 86400000L) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeUInt64Size(5, this.resendIntervalForValidResponse);
        }
        if (this.resendIntervalForInvalidResponse != 3600000L) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeUInt64Size(6, this.resendIntervalForInvalidResponse);
        }
        if (this.validResponseCodes != null && this.validResponseCodes.length > 0) {
          int dataSize = 0;
          for (int i = 0; i < this.validResponseCodes.length; i++) {
            int element = this.validResponseCodes[i];
            dataSize += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
                .computeUInt32SizeNoTag(element);
          }
          size += dataSize;
          size += 1 * this.validResponseCodes.length;
        }
        if (this.reportEventEnabled != true) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBoolSize(8, this.reportEventEnabled);
        }
        if (!this.reportUrl.equals("")) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(9, this.reportUrl);
        }
        return size;
      }

      @Override
      public Request mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.type = input.readBytes();
              break;
            }
            case 18: {
              if (this.preconditions == null) {
                this.preconditions = new IdSyncProtobuf.IdSyncConfig.Preconditions();
              }
              input.readMessage(this.preconditions);
              break;
            }
            case 26: {
              this.url = input.readBytes();
              break;
            }
            case 34: {
              int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 34);
              int i = this.headers == null ? 0 : this.headers.length;
              IdSyncProtobuf.IdSyncConfig.Header[] newArray =
                  new IdSyncProtobuf.IdSyncConfig.Header[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.headers, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = new IdSyncProtobuf.IdSyncConfig.Header();
                input.readMessage(newArray[i]);
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = new IdSyncProtobuf.IdSyncConfig.Header();
              input.readMessage(newArray[i]);
              this.headers = newArray;
              break;
            }
            case 40: {
              this.resendIntervalForValidResponse = input.readUInt64();
              break;
            }
            case 48: {
              this.resendIntervalForInvalidResponse = input.readUInt64();
              break;
            }
            case 56: {
              int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 56);
              int i = this.validResponseCodes == null ? 0 : this.validResponseCodes.length;
              int[] newArray = new int[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.validResponseCodes, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = input.readUInt32();
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = input.readUInt32();
              this.validResponseCodes = newArray;
              break;
            }
            case 58: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              // First pass to compute array length.
              int arrayLength = 0;
              int startPos = input.getPosition();
              while (input.getBytesUntilLimit() > 0) {
                input.readUInt32();
                arrayLength++;
              }
              input.rewindToPosition(startPos);
              int i = this.validResponseCodes == null ? 0 : this.validResponseCodes.length;
              int[] newArray = new int[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.validResponseCodes, 0, newArray, 0, i);
              }
              for (; i < newArray.length; i++) {
                newArray[i] = input.readUInt32();
              }
              this.validResponseCodes = newArray;
              input.popLimit(limit);
              break;
            }
            case 64: {
              this.reportEventEnabled = input.readBool();
              break;
            }
            case 74: {
              this.reportUrl = input.readString();
              break;
            }
          }
        }
      }

      public static Request parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Request(), data);
      }

      public static Request parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Request().mergeFrom(input);
      }
    }

    public static final class RequestConfig extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile RequestConfig[] _emptyArray;
      public static RequestConfig[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new RequestConfig[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional uint64 launch_delay = 1 [default = 10000];
      public long launchDelay;

      // repeated .IdSyncConfig.Request requests = 2;
      public IdSyncProtobuf.IdSyncConfig.Request[] requests;

      public RequestConfig() {
        clear();
      }

      public RequestConfig clear() {
        launchDelay = 10000L;
        requests = IdSyncProtobuf.IdSyncConfig.Request.emptyArray();
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.launchDelay != 10000L) {
          output.writeUInt64(1, this.launchDelay);
        }
        if (this.requests != null && this.requests.length > 0) {
          for (int i = 0; i < this.requests.length; i++) {
            IdSyncProtobuf.IdSyncConfig.Request element = this.requests[i];
            if (element != null) {
              output.writeMessage(2, element);
            }
          }
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.launchDelay != 10000L) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeUInt64Size(1, this.launchDelay);
        }
        if (this.requests != null && this.requests.length > 0) {
          for (int i = 0; i < this.requests.length; i++) {
            IdSyncProtobuf.IdSyncConfig.Request element = this.requests[i];
            if (element != null) {
              size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
                .computeMessageSize(2, element);
            }
          }
        }
        return size;
      }

      @Override
      public RequestConfig mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              this.launchDelay = input.readUInt64();
              break;
            }
            case 18: {
              int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 18);
              int i = this.requests == null ? 0 : this.requests.length;
              IdSyncProtobuf.IdSyncConfig.Request[] newArray =
                  new IdSyncProtobuf.IdSyncConfig.Request[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.requests, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = new IdSyncProtobuf.IdSyncConfig.Request();
                input.readMessage(newArray[i]);
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = new IdSyncProtobuf.IdSyncConfig.Request();
              input.readMessage(newArray[i]);
              this.requests = newArray;
              break;
            }
          }
        }
      }

      public static RequestConfig parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new RequestConfig(), data);
      }

      public static RequestConfig parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new RequestConfig().mergeFrom(input);
      }
    }

    private static volatile IdSyncConfig[] _emptyArray;
    public static IdSyncConfig[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new IdSyncConfig[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bool enabled = 1 [default = false];
    public boolean enabled;

    // optional .IdSyncConfig.RequestConfig request_config = 2;
    public IdSyncProtobuf.IdSyncConfig.RequestConfig requestConfig;

    public IdSyncConfig() {
      clear();
    }

    public IdSyncConfig clear() {
      enabled = false;
      requestConfig = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.enabled != false) {
        output.writeBool(1, this.enabled);
      }
      if (this.requestConfig != null) {
        output.writeMessage(2, this.requestConfig);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.enabled != false) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(1, this.enabled);
      }
      if (this.requestConfig != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.requestConfig);
      }
      return size;
    }

    @Override
    public IdSyncConfig mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.enabled = input.readBool();
            break;
          }
          case 18: {
            if (this.requestConfig == null) {
              this.requestConfig = new IdSyncProtobuf.IdSyncConfig.RequestConfig();
            }
            input.readMessage(this.requestConfig);
            break;
          }
        }
      }
    }

    public static IdSyncConfig parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new IdSyncConfig(), data);
    }

    public static IdSyncConfig parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new IdSyncConfig().mergeFrom(input);
    }
  }
}
