// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.appmetrica.analytics.remotepermissions.impl.protobuf.client;

@SuppressWarnings("hiding")
public interface RemotePermissionsProtobuf {

  public static final class RemotePermissions extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile RemotePermissions[] _emptyArray;
    public static RemotePermissions[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RemotePermissions[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated bytes permissions = 1;
    public byte[][] permissions;

    public RemotePermissions() {
      clear();
    }

    public RemotePermissions clear() {
      permissions = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.permissions != null && this.permissions.length > 0) {
        for (int i = 0; i < this.permissions.length; i++) {
          byte[] element = this.permissions[i];
          if (element != null) {
            output.writeBytes(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.permissions != null && this.permissions.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.permissions.length; i++) {
          byte[] element = this.permissions[i];
          if (element != null) {
            dataCount++;
            dataSize += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
                .computeBytesSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      return size;
    }

    @Override
    public RemotePermissions mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.permissions == null ? 0 : this.permissions.length;
            byte[][] newArray = new byte[i + arrayLength][];
            if (i != 0) {
              java.lang.System.arraycopy(this.permissions, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readBytes();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readBytes();
            this.permissions = newArray;
            break;
          }
        }
      }
    }

    public static RemotePermissions parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new RemotePermissions(), data);
    }

    public static RemotePermissions parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RemotePermissions().mergeFrom(input);
    }
  }
}
