// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.appmetrica.analytics.apphud.impl.protobuf.client;

@SuppressWarnings("hiding")
public interface ModuleConfigProtobuf {

  public static final class ModuleConfig extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile ModuleConfig[] _emptyArray;
    public static ModuleConfig[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ModuleConfig[0];
          }
        }
      }
      return _emptyArray;
    }

    // required string apiKey = 1 [default = ""];
    public java.lang.String apiKey;

    public ModuleConfig() {
      clear();
    }

    public ModuleConfig clear() {
      apiKey = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeString(1, this.apiKey);
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.apiKey);
      return size;
    }

    @Override
    public ModuleConfig mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.apiKey = input.readString();
            break;
          }
        }
      }
    }

    public static ModuleConfig parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new ModuleConfig(), data);
    }

    public static ModuleConfig parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ModuleConfig().mergeFrom(input);
    }
  }
}
