// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.appmetrica.analytics.impl.protobuf.backend;

@SuppressWarnings("hiding")
public final class AdRevenue extends
    io.appmetrica.analytics.protobuf.nano.MessageNano {

  // enum AdType
  public static final int UNKNOWN = 0;
  public static final int NATIVE = 1;
  public static final int BANNER = 2;
  public static final int REWARDED = 3;
  public static final int INTERSTITIAL = 4;
  public static final int MREC = 5;
  public static final int OTHER = 6;

  public static final class Decimal extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile Decimal[] _emptyArray;
    public static Decimal[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Decimal[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 mantissa = 1 [default = 0];
    public long mantissa;

    // optional int32 exponent = 2 [default = 0];
    public int exponent;

    public Decimal() {
      clear();
    }

    public Decimal clear() {
      mantissa = 0L;
      exponent = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.mantissa != 0L) {
        output.writeInt64(1, this.mantissa);
      }
      if (this.exponent != 0) {
        output.writeInt32(2, this.exponent);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.mantissa != 0L) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.mantissa);
      }
      if (this.exponent != 0) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.exponent);
      }
      return size;
    }

    @Override
    public Decimal mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.mantissa = input.readInt64();
            break;
          }
          case 16: {
            this.exponent = input.readInt32();
            break;
          }
        }
      }
    }

    public static Decimal parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Decimal(), data);
    }

    public static Decimal parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Decimal().mergeFrom(input);
    }
  }

  private static volatile AdRevenue[] _emptyArray;
  public static AdRevenue[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new AdRevenue[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional bytes data_source = 1 [default = "manual"];
  private static byte[] _dataSourceDefault;
  public byte[] dataSource;

  // optional .AdRevenue.Decimal ad_revenue = 2;
  public AdRevenue.Decimal adRevenue;

  // optional bytes currency = 3;
  public byte[] currency;

  // optional .AdRevenue.AdType ad_type = 4 [default = UNKNOWN];
  public int adType;

  // optional bytes ad_network = 5;
  public byte[] adNetwork;

  // optional bytes ad_unit_id = 6;
  public byte[] adUnitId;

  // optional bytes ad_unit_name = 7;
  public byte[] adUnitName;

  // optional bytes ad_placement_id = 8;
  public byte[] adPlacementId;

  // optional bytes ad_placement_name = 9;
  public byte[] adPlacementName;

  // optional bytes precision = 10;
  public byte[] precision;

  // optional bytes payload = 11;
  public byte[] payload;

  private static volatile boolean _classInitialized;

  public AdRevenue() {
    // Lazily initializes the field defaults
    if (!_classInitialized) {
      synchronized (
          io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (!_classInitialized) {
          _dataSourceDefault = io.appmetrica.analytics.protobuf.nano.InternalNano.bytesDefaultValue("manual");
          _classInitialized = true;
        }
      }
    }
    clear();
  }

  public AdRevenue clear() {
    dataSource = _dataSourceDefault.clone();
    adRevenue = null;
    currency = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
    adType = AdRevenue.UNKNOWN;
    adNetwork = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
    adUnitId = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
    adUnitName = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
    adPlacementId = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
    adPlacementName = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
    precision = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
    payload = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (!java.util.Arrays.equals(this.dataSource, _dataSourceDefault)) {
      output.writeBytes(1, this.dataSource);
    }
    if (this.adRevenue != null) {
      output.writeMessage(2, this.adRevenue);
    }
    if (!java.util.Arrays.equals(this.currency, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      output.writeBytes(3, this.currency);
    }
    if (this.adType != AdRevenue.UNKNOWN) {
      output.writeInt32(4, this.adType);
    }
    if (!java.util.Arrays.equals(this.adNetwork, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      output.writeBytes(5, this.adNetwork);
    }
    if (!java.util.Arrays.equals(this.adUnitId, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      output.writeBytes(6, this.adUnitId);
    }
    if (!java.util.Arrays.equals(this.adUnitName, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      output.writeBytes(7, this.adUnitName);
    }
    if (!java.util.Arrays.equals(this.adPlacementId, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      output.writeBytes(8, this.adPlacementId);
    }
    if (!java.util.Arrays.equals(this.adPlacementName, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      output.writeBytes(9, this.adPlacementName);
    }
    if (!java.util.Arrays.equals(this.precision, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      output.writeBytes(10, this.precision);
    }
    if (!java.util.Arrays.equals(this.payload, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      output.writeBytes(11, this.payload);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (!java.util.Arrays.equals(this.dataSource, _dataSourceDefault)) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeBytesSize(1, this.dataSource);
    }
    if (this.adRevenue != null) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
        .computeMessageSize(2, this.adRevenue);
    }
    if (!java.util.Arrays.equals(this.currency, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeBytesSize(3, this.currency);
    }
    if (this.adType != AdRevenue.UNKNOWN) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
        .computeInt32Size(4, this.adType);
    }
    if (!java.util.Arrays.equals(this.adNetwork, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeBytesSize(5, this.adNetwork);
    }
    if (!java.util.Arrays.equals(this.adUnitId, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeBytesSize(6, this.adUnitId);
    }
    if (!java.util.Arrays.equals(this.adUnitName, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeBytesSize(7, this.adUnitName);
    }
    if (!java.util.Arrays.equals(this.adPlacementId, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeBytesSize(8, this.adPlacementId);
    }
    if (!java.util.Arrays.equals(this.adPlacementName, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeBytesSize(9, this.adPlacementName);
    }
    if (!java.util.Arrays.equals(this.precision, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeBytesSize(10, this.precision);
    }
    if (!java.util.Arrays.equals(this.payload, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeBytesSize(11, this.payload);
    }
    return size;
  }

  @Override
  public AdRevenue mergeFrom(
          io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 10: {
          this.dataSource = input.readBytes();
          break;
        }
        case 18: {
          if (this.adRevenue == null) {
            this.adRevenue = new AdRevenue.Decimal();
          }
          input.readMessage(this.adRevenue);
          break;
        }
        case 26: {
          this.currency = input.readBytes();
          break;
        }
        case 32: {
          int value = input.readInt32();
          switch (value) {
            case AdRevenue.UNKNOWN:
            case AdRevenue.NATIVE:
            case AdRevenue.BANNER:
            case AdRevenue.REWARDED:
            case AdRevenue.INTERSTITIAL:
            case AdRevenue.MREC:
            case AdRevenue.OTHER:
              this.adType = value;
              break;
          }
          break;
        }
        case 42: {
          this.adNetwork = input.readBytes();
          break;
        }
        case 50: {
          this.adUnitId = input.readBytes();
          break;
        }
        case 58: {
          this.adUnitName = input.readBytes();
          break;
        }
        case 66: {
          this.adPlacementId = input.readBytes();
          break;
        }
        case 74: {
          this.adPlacementName = input.readBytes();
          break;
        }
        case 82: {
          this.precision = input.readBytes();
          break;
        }
        case 90: {
          this.payload = input.readBytes();
          break;
        }
      }
    }
  }

  public static AdRevenue parseFrom(byte[] data)
      throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
    return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new AdRevenue(), data);
  }

  public static AdRevenue parseFrom(
          io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new AdRevenue().mergeFrom(input);
  }
}
