// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.appmetrica.analytics.impl.protobuf.backend;

@SuppressWarnings("hiding")
public interface CrashAndroid {

  // enum OptionalBool
  public static final int OPTIONAL_BOOL_UNDEFINED = -1;
  public static final int OPTIONAL_BOOL_FALSE = 0;
  public static final int OPTIONAL_BOOL_TRUE = 1;

  // enum NativeCrashSource
  public static final int UNKNOWN = 0;
  public static final int USER = 1;
  public static final int CRASHPAD = 3;

  public static final class BytesPair extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile BytesPair[] _emptyArray;
    public static BytesPair[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new BytesPair[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bytes key = 1;
    public byte[] key;

    // optional bytes value = 2;
    public byte[] value;

    public BytesPair() {
      clear();
    }

    public BytesPair clear() {
      key = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      value = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!java.util.Arrays.equals(this.key, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(1, this.key);
      }
      if (!java.util.Arrays.equals(this.value, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(2, this.value);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!java.util.Arrays.equals(this.key, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.key);
      }
      if (!java.util.Arrays.equals(this.value, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(2, this.value);
      }
      return size;
    }

    @Override
    public BytesPair mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.key = input.readBytes();
            break;
          }
          case 18: {
            this.value = input.readBytes();
            break;
          }
        }
      }
    }

    public static BytesPair parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new BytesPair(), data);
    }

    public static BytesPair parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new BytesPair().mergeFrom(input);
    }
  }

  public static final class StackTraceElement extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile StackTraceElement[] _emptyArray;
    public static StackTraceElement[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new StackTraceElement[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string class_name = 1;
    public java.lang.String className;

    // optional string file_name = 2;
    public java.lang.String fileName;

    // optional sint32 line_number = 3 [default = -1];
    public int lineNumber;

    // optional string method_name = 4;
    public java.lang.String methodName;

    // optional bool is_native = 5;
    public boolean isNative;

    // optional sint32 column_number = 6 [default = -1];
    public int columnNumber;

    public StackTraceElement() {
      clear();
    }

    public StackTraceElement clear() {
      className = "";
      fileName = "";
      lineNumber = -1;
      methodName = "";
      isNative = false;
      columnNumber = -1;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.className.equals("")) {
        output.writeString(1, this.className);
      }
      if (!this.fileName.equals("")) {
        output.writeString(2, this.fileName);
      }
      if (this.lineNumber != -1) {
        output.writeSInt32(3, this.lineNumber);
      }
      if (!this.methodName.equals("")) {
        output.writeString(4, this.methodName);
      }
      if (this.isNative != false) {
        output.writeBool(5, this.isNative);
      }
      if (this.columnNumber != -1) {
        output.writeSInt32(6, this.columnNumber);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.className.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.className);
      }
      if (!this.fileName.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.fileName);
      }
      if (this.lineNumber != -1) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeSInt32Size(3, this.lineNumber);
      }
      if (!this.methodName.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.methodName);
      }
      if (this.isNative != false) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(5, this.isNative);
      }
      if (this.columnNumber != -1) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeSInt32Size(6, this.columnNumber);
      }
      return size;
    }

    @Override
    public StackTraceElement mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.className = input.readString();
            break;
          }
          case 18: {
            this.fileName = input.readString();
            break;
          }
          case 24: {
            this.lineNumber = input.readSInt32();
            break;
          }
          case 34: {
            this.methodName = input.readString();
            break;
          }
          case 40: {
            this.isNative = input.readBool();
            break;
          }
          case 48: {
            this.columnNumber = input.readSInt32();
            break;
          }
        }
      }
    }

    public static StackTraceElement parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new StackTraceElement(), data);
    }

    public static StackTraceElement parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new StackTraceElement().mergeFrom(input);
    }
  }

  public static final class Thread extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile Thread[] _emptyArray;
    public static Thread[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Thread[0];
          }
        }
      }
      return _emptyArray;
    }

    // required string name = 1;
    public java.lang.String name;

    // required sint32 priority = 2;
    public int priority;

    // required sint64 tid = 3;
    public long tid;

    // optional string group = 4;
    public java.lang.String group;

    // optional uint32 state = 5;
    public int state;

    // repeated .StackTraceElement stacktrace = 6;
    public CrashAndroid.StackTraceElement[] stacktrace;

    public Thread() {
      clear();
    }

    public Thread clear() {
      name = "";
      priority = 0;
      tid = 0L;
      group = "";
      state = 0;
      stacktrace = CrashAndroid.StackTraceElement.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeString(1, this.name);
      output.writeSInt32(2, this.priority);
      output.writeSInt64(3, this.tid);
      if (!this.group.equals("")) {
        output.writeString(4, this.group);
      }
      if (this.state != 0) {
        output.writeUInt32(5, this.state);
      }
      if (this.stacktrace != null && this.stacktrace.length > 0) {
        for (int i = 0; i < this.stacktrace.length; i++) {
          CrashAndroid.StackTraceElement element = this.stacktrace[i];
          if (element != null) {
            output.writeMessage(6, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.name);
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeSInt32Size(2, this.priority);
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeSInt64Size(3, this.tid);
      if (!this.group.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.group);
      }
      if (this.state != 0) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(5, this.state);
      }
      if (this.stacktrace != null && this.stacktrace.length > 0) {
        for (int i = 0; i < this.stacktrace.length; i++) {
          CrashAndroid.StackTraceElement element = this.stacktrace[i];
          if (element != null) {
            size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(6, element);
          }
        }
      }
      return size;
    }

    @Override
    public Thread mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.name = input.readString();
            break;
          }
          case 16: {
            this.priority = input.readSInt32();
            break;
          }
          case 24: {
            this.tid = input.readSInt64();
            break;
          }
          case 34: {
            this.group = input.readString();
            break;
          }
          case 40: {
            this.state = input.readUInt32();
            break;
          }
          case 50: {
            int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 50);
            int i = this.stacktrace == null ? 0 : this.stacktrace.length;
            CrashAndroid.StackTraceElement[] newArray =
                new CrashAndroid.StackTraceElement[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.stacktrace, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new CrashAndroid.StackTraceElement();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new CrashAndroid.StackTraceElement();
            input.readMessage(newArray[i]);
            this.stacktrace = newArray;
            break;
          }
        }
      }
    }

    public static Thread parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Thread(), data);
    }

    public static Thread parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Thread().mergeFrom(input);
    }
  }

  public static final class AllThreads extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile AllThreads[] _emptyArray;
    public static AllThreads[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new AllThreads[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .Thread affected_thread = 1;
    public CrashAndroid.Thread affectedThread;

    // repeated .Thread threads = 2;
    public CrashAndroid.Thread[] threads;

    // optional string process_name = 3;
    public java.lang.String processName;

    public AllThreads() {
      clear();
    }

    public AllThreads clear() {
      affectedThread = null;
      threads = CrashAndroid.Thread.emptyArray();
      processName = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.affectedThread != null) {
        output.writeMessage(1, this.affectedThread);
      }
      if (this.threads != null && this.threads.length > 0) {
        for (int i = 0; i < this.threads.length; i++) {
          CrashAndroid.Thread element = this.threads[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      if (!this.processName.equals("")) {
        output.writeString(3, this.processName);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.affectedThread != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.affectedThread);
      }
      if (this.threads != null && this.threads.length > 0) {
        for (int i = 0; i < this.threads.length; i++) {
          CrashAndroid.Thread element = this.threads[i];
          if (element != null) {
            size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      if (!this.processName.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.processName);
      }
      return size;
    }

    @Override
    public AllThreads mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.affectedThread == null) {
              this.affectedThread = new CrashAndroid.Thread();
            }
            input.readMessage(this.affectedThread);
            break;
          }
          case 18: {
            int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.threads == null ? 0 : this.threads.length;
            CrashAndroid.Thread[] newArray =
                new CrashAndroid.Thread[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.threads, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new CrashAndroid.Thread();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new CrashAndroid.Thread();
            input.readMessage(newArray[i]);
            this.threads = newArray;
            break;
          }
          case 26: {
            this.processName = input.readString();
            break;
          }
        }
      }
    }

    public static AllThreads parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new AllThreads(), data);
    }

    public static AllThreads parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new AllThreads().mergeFrom(input);
    }
  }

  public static final class Throwable extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile Throwable[] _emptyArray;
    public static Throwable[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Throwable[0];
          }
        }
      }
      return _emptyArray;
    }

    // required string exception_class = 1;
    public java.lang.String exceptionClass;

    // optional string message = 2;
    public java.lang.String message;

    // repeated .StackTraceElement backtrace = 3;
    public CrashAndroid.StackTraceElement[] backtrace;

    // optional .Throwable cause = 4;
    public CrashAndroid.Throwable cause;

    // repeated .Throwable suppressed = 5;
    public CrashAndroid.Throwable[] suppressed;

    public Throwable() {
      clear();
    }

    public Throwable clear() {
      exceptionClass = "";
      message = "";
      backtrace = CrashAndroid.StackTraceElement.emptyArray();
      cause = null;
      suppressed = CrashAndroid.Throwable.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeString(1, this.exceptionClass);
      if (!this.message.equals("")) {
        output.writeString(2, this.message);
      }
      if (this.backtrace != null && this.backtrace.length > 0) {
        for (int i = 0; i < this.backtrace.length; i++) {
          CrashAndroid.StackTraceElement element = this.backtrace[i];
          if (element != null) {
            output.writeMessage(3, element);
          }
        }
      }
      if (this.cause != null) {
        output.writeMessage(4, this.cause);
      }
      if (this.suppressed != null && this.suppressed.length > 0) {
        for (int i = 0; i < this.suppressed.length; i++) {
          CrashAndroid.Throwable element = this.suppressed[i];
          if (element != null) {
            output.writeMessage(5, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.exceptionClass);
      if (!this.message.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.message);
      }
      if (this.backtrace != null && this.backtrace.length > 0) {
        for (int i = 0; i < this.backtrace.length; i++) {
          CrashAndroid.StackTraceElement element = this.backtrace[i];
          if (element != null) {
            size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(3, element);
          }
        }
      }
      if (this.cause != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(4, this.cause);
      }
      if (this.suppressed != null && this.suppressed.length > 0) {
        for (int i = 0; i < this.suppressed.length; i++) {
          CrashAndroid.Throwable element = this.suppressed[i];
          if (element != null) {
            size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(5, element);
          }
        }
      }
      return size;
    }

    @Override
    public Throwable mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.exceptionClass = input.readString();
            break;
          }
          case 18: {
            this.message = input.readString();
            break;
          }
          case 26: {
            int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.backtrace == null ? 0 : this.backtrace.length;
            CrashAndroid.StackTraceElement[] newArray =
                new CrashAndroid.StackTraceElement[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.backtrace, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new CrashAndroid.StackTraceElement();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new CrashAndroid.StackTraceElement();
            input.readMessage(newArray[i]);
            this.backtrace = newArray;
            break;
          }
          case 34: {
            if (this.cause == null) {
              this.cause = new CrashAndroid.Throwable();
            }
            input.readMessage(this.cause);
            break;
          }
          case 42: {
            int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 42);
            int i = this.suppressed == null ? 0 : this.suppressed.length;
            CrashAndroid.Throwable[] newArray =
                new CrashAndroid.Throwable[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.suppressed, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new CrashAndroid.Throwable();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new CrashAndroid.Throwable();
            input.readMessage(newArray[i]);
            this.suppressed = newArray;
            break;
          }
        }
      }
    }

    public static Throwable parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Throwable(), data);
    }

    public static Throwable parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Throwable().mergeFrom(input);
    }
  }

  public static final class Anr extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile Anr[] _emptyArray;
    public static Anr[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Anr[0];
          }
        }
      }
      return _emptyArray;
    }

    // required .AllThreads threads = 1;
    public CrashAndroid.AllThreads threads;

    // optional string buildId = 2;
    public java.lang.String buildId;

    // optional .OptionalBool isOffline = 3;
    public int isOffline;

    public Anr() {
      clear();
    }

    public Anr clear() {
      threads = null;
      buildId = "";
      isOffline = CrashAndroid.OPTIONAL_BOOL_UNDEFINED;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.threads != null) {
        output.writeMessage(1, this.threads);
      }
      if (!this.buildId.equals("")) {
        output.writeString(2, this.buildId);
      }
      if (this.isOffline != CrashAndroid.OPTIONAL_BOOL_UNDEFINED) {
        output.writeInt32(3, this.isOffline);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.threads != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.threads);
      }
      if (!this.buildId.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.buildId);
      }
      if (this.isOffline != CrashAndroid.OPTIONAL_BOOL_UNDEFINED) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(3, this.isOffline);
      }
      return size;
    }

    @Override
    public Anr mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.threads == null) {
              this.threads = new CrashAndroid.AllThreads();
            }
            input.readMessage(this.threads);
            break;
          }
          case 18: {
            this.buildId = input.readString();
            break;
          }
          case 24: {
            int value = input.readInt32();
            switch (value) {
              case CrashAndroid.OPTIONAL_BOOL_UNDEFINED:
              case CrashAndroid.OPTIONAL_BOOL_FALSE:
              case CrashAndroid.OPTIONAL_BOOL_TRUE:
                this.isOffline = value;
                break;
            }
            break;
          }
        }
      }
    }

    public static Anr parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Anr(), data);
    }

    public static Anr parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Anr().mergeFrom(input);
    }
  }

  public static final class NativeCrashHandler extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile NativeCrashHandler[] _emptyArray;
    public static NativeCrashHandler[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new NativeCrashHandler[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .NativeCrashSource source = 1 [default = UNKNOWN];
    public int source;

    // optional string version = 2 [default = ""];
    public java.lang.String version;

    public NativeCrashHandler() {
      clear();
    }

    public NativeCrashHandler clear() {
      source = CrashAndroid.UNKNOWN;
      version = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.source != CrashAndroid.UNKNOWN) {
        output.writeInt32(1, this.source);
      }
      if (!this.version.equals("")) {
        output.writeString(2, this.version);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.source != CrashAndroid.UNKNOWN) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.source);
      }
      if (!this.version.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.version);
      }
      return size;
    }

    @Override
    public NativeCrashHandler mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case CrashAndroid.UNKNOWN:
              case CrashAndroid.USER:
              case CrashAndroid.CRASHPAD:
                this.source = value;
                break;
            }
            break;
          }
          case 18: {
            this.version = input.readString();
            break;
          }
        }
      }
    }

    public static NativeCrashHandler parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new NativeCrashHandler(), data);
    }

    public static NativeCrashHandler parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new NativeCrashHandler().mergeFrom(input);
    }
  }

  public static final class Crash extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    // enum CrashType
    public static final int VIRTUAL_MACHINE = 0;
    public static final int NATIVE = 1;

    public static final class NativeCrash extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile NativeCrash[] _emptyArray;
      public static NativeCrash[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new NativeCrash[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional bytes nativeCrashPayload = 1;
      public byte[] nativeCrashPayload;

      // optional .NativeCrashHandler handler = 2;
      public CrashAndroid.NativeCrashHandler handler;

      public NativeCrash() {
        clear();
      }

      public NativeCrash clear() {
        nativeCrashPayload = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
        handler = null;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!java.util.Arrays.equals(this.nativeCrashPayload, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          output.writeBytes(1, this.nativeCrashPayload);
        }
        if (this.handler != null) {
          output.writeMessage(2, this.handler);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!java.util.Arrays.equals(this.nativeCrashPayload, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBytesSize(1, this.nativeCrashPayload);
        }
        if (this.handler != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(2, this.handler);
        }
        return size;
      }

      @Override
      public NativeCrash mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.nativeCrashPayload = input.readBytes();
              break;
            }
            case 18: {
              if (this.handler == null) {
                this.handler = new CrashAndroid.NativeCrashHandler();
              }
              input.readMessage(this.handler);
              break;
            }
          }
        }
      }

      public static NativeCrash parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new NativeCrash(), data);
      }

      public static NativeCrash parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new NativeCrash().mergeFrom(input);
      }
    }

    private static volatile Crash[] _emptyArray;
    public static Crash[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Crash[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .Throwable throwable = 1;
    public CrashAndroid.Throwable throwable;

    // optional .AllThreads threads = 2;
    public CrashAndroid.AllThreads threads;

    // optional string buildId = 3;
    public java.lang.String buildId;

    // optional .OptionalBool isOffline = 4;
    public int isOffline;

    // repeated .StackTraceElement methodCallStacktrace = 5;
    public CrashAndroid.StackTraceElement[] methodCallStacktrace;

    // optional .Crash.CrashType type = 6 [default = VIRTUAL_MACHINE];
    public int type;

    // optional .Crash.NativeCrash native = 7;
    public CrashAndroid.Crash.NativeCrash native_;

    // optional bytes virtual_machine = 8 [default = "JVM"];
    private static byte[] _virtualMachineDefault;
    public byte[] virtualMachine;

    // optional bytes virtual_machine_version = 9;
    public byte[] virtualMachineVersion;

    // repeated .BytesPair plugin_environment = 10;
    public CrashAndroid.BytesPair[] pluginEnvironment;

    private static volatile boolean _classInitialized;

    public Crash() {
      // Lazily initializes the field defaults
      if (!_classInitialized) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (!_classInitialized) {
            _virtualMachineDefault = io.appmetrica.analytics.protobuf.nano.InternalNano.bytesDefaultValue("JVM");
            _classInitialized = true;
          }
        }
      }
      clear();
    }

    public Crash clear() {
      throwable = null;
      threads = null;
      buildId = "";
      isOffline = CrashAndroid.OPTIONAL_BOOL_UNDEFINED;
      methodCallStacktrace = CrashAndroid.StackTraceElement.emptyArray();
      type = CrashAndroid.Crash.VIRTUAL_MACHINE;
      native_ = null;
      virtualMachine = _virtualMachineDefault.clone();
      virtualMachineVersion = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      pluginEnvironment = CrashAndroid.BytesPair.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.throwable != null) {
        output.writeMessage(1, this.throwable);
      }
      if (this.threads != null) {
        output.writeMessage(2, this.threads);
      }
      if (!this.buildId.equals("")) {
        output.writeString(3, this.buildId);
      }
      if (this.isOffline != CrashAndroid.OPTIONAL_BOOL_UNDEFINED) {
        output.writeInt32(4, this.isOffline);
      }
      if (this.methodCallStacktrace != null && this.methodCallStacktrace.length > 0) {
        for (int i = 0; i < this.methodCallStacktrace.length; i++) {
          CrashAndroid.StackTraceElement element = this.methodCallStacktrace[i];
          if (element != null) {
            output.writeMessage(5, element);
          }
        }
      }
      if (this.type != CrashAndroid.Crash.VIRTUAL_MACHINE) {
        output.writeInt32(6, this.type);
      }
      if (this.native_ != null) {
        output.writeMessage(7, this.native_);
      }
      if (!java.util.Arrays.equals(this.virtualMachine, _virtualMachineDefault)) {
        output.writeBytes(8, this.virtualMachine);
      }
      if (!java.util.Arrays.equals(this.virtualMachineVersion, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(9, this.virtualMachineVersion);
      }
      if (this.pluginEnvironment != null && this.pluginEnvironment.length > 0) {
        for (int i = 0; i < this.pluginEnvironment.length; i++) {
          CrashAndroid.BytesPair element = this.pluginEnvironment[i];
          if (element != null) {
            output.writeMessage(10, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.throwable != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.throwable);
      }
      if (this.threads != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.threads);
      }
      if (!this.buildId.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.buildId);
      }
      if (this.isOffline != CrashAndroid.OPTIONAL_BOOL_UNDEFINED) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(4, this.isOffline);
      }
      if (this.methodCallStacktrace != null && this.methodCallStacktrace.length > 0) {
        for (int i = 0; i < this.methodCallStacktrace.length; i++) {
          CrashAndroid.StackTraceElement element = this.methodCallStacktrace[i];
          if (element != null) {
            size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(5, element);
          }
        }
      }
      if (this.type != CrashAndroid.Crash.VIRTUAL_MACHINE) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(6, this.type);
      }
      if (this.native_ != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(7, this.native_);
      }
      if (!java.util.Arrays.equals(this.virtualMachine, _virtualMachineDefault)) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(8, this.virtualMachine);
      }
      if (!java.util.Arrays.equals(this.virtualMachineVersion, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(9, this.virtualMachineVersion);
      }
      if (this.pluginEnvironment != null && this.pluginEnvironment.length > 0) {
        for (int i = 0; i < this.pluginEnvironment.length; i++) {
          CrashAndroid.BytesPair element = this.pluginEnvironment[i];
          if (element != null) {
            size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(10, element);
          }
        }
      }
      return size;
    }

    @Override
    public Crash mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.throwable == null) {
              this.throwable = new CrashAndroid.Throwable();
            }
            input.readMessage(this.throwable);
            break;
          }
          case 18: {
            if (this.threads == null) {
              this.threads = new CrashAndroid.AllThreads();
            }
            input.readMessage(this.threads);
            break;
          }
          case 26: {
            this.buildId = input.readString();
            break;
          }
          case 32: {
            int value = input.readInt32();
            switch (value) {
              case CrashAndroid.OPTIONAL_BOOL_UNDEFINED:
              case CrashAndroid.OPTIONAL_BOOL_FALSE:
              case CrashAndroid.OPTIONAL_BOOL_TRUE:
                this.isOffline = value;
                break;
            }
            break;
          }
          case 42: {
            int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 42);
            int i = this.methodCallStacktrace == null ? 0 : this.methodCallStacktrace.length;
            CrashAndroid.StackTraceElement[] newArray =
                new CrashAndroid.StackTraceElement[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.methodCallStacktrace, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new CrashAndroid.StackTraceElement();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new CrashAndroid.StackTraceElement();
            input.readMessage(newArray[i]);
            this.methodCallStacktrace = newArray;
            break;
          }
          case 48: {
            int value = input.readInt32();
            switch (value) {
              case CrashAndroid.Crash.VIRTUAL_MACHINE:
              case CrashAndroid.Crash.NATIVE:
                this.type = value;
                break;
            }
            break;
          }
          case 58: {
            if (this.native_ == null) {
              this.native_ = new CrashAndroid.Crash.NativeCrash();
            }
            input.readMessage(this.native_);
            break;
          }
          case 66: {
            this.virtualMachine = input.readBytes();
            break;
          }
          case 74: {
            this.virtualMachineVersion = input.readBytes();
            break;
          }
          case 82: {
            int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 82);
            int i = this.pluginEnvironment == null ? 0 : this.pluginEnvironment.length;
            CrashAndroid.BytesPair[] newArray =
                new CrashAndroid.BytesPair[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.pluginEnvironment, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new CrashAndroid.BytesPair();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new CrashAndroid.BytesPair();
            input.readMessage(newArray[i]);
            this.pluginEnvironment = newArray;
            break;
          }
        }
      }
    }

    public static Crash parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Crash(), data);
    }

    public static Crash parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Crash().mergeFrom(input);
    }
  }

  public static final class Error extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    // enum ErrorType
    public static final int DEFAULT = 0;
    public static final int CUSTOM = 1;

    public static final class Custom extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile Custom[] _emptyArray;
      public static Custom[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Custom[0];
            }
          }
        }
        return _emptyArray;
      }

      // required string identifier = 1;
      public java.lang.String identifier;

      public Custom() {
        clear();
      }

      public Custom clear() {
        identifier = "";
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        output.writeString(1, this.identifier);
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.identifier);
        return size;
      }

      @Override
      public Custom mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.identifier = input.readString();
              break;
            }
          }
        }
      }

      public static Custom parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Custom(), data);
      }

      public static Custom parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Custom().mergeFrom(input);
      }
    }

    private static volatile Error[] _emptyArray;
    public static Error[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Error[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .Throwable throwable = 1;
    public CrashAndroid.Throwable throwable;

    // optional .AllThreads threads = 2;
    public CrashAndroid.AllThreads threads;

    // optional string buildId = 3;
    public java.lang.String buildId;

    // optional .OptionalBool isOffline = 4;
    public int isOffline;

    // repeated .StackTraceElement methodCallStacktrace = 5;
    public CrashAndroid.StackTraceElement[] methodCallStacktrace;

    // optional string message = 6;
    public java.lang.String message;

    // optional .Error.ErrorType type = 7 [default = DEFAULT];
    public int type;

    // optional .Error.Custom custom = 8;
    public CrashAndroid.Error.Custom custom;

    // optional bytes virtual_machine = 9 [default = "JVM"];
    private static byte[] _virtualMachineDefault;
    public byte[] virtualMachine;

    // optional bytes virtual_machine_version = 10;
    public byte[] virtualMachineVersion;

    // repeated .BytesPair plugin_environment = 11;
    public CrashAndroid.BytesPair[] pluginEnvironment;

    private static volatile boolean _classInitialized;

    public Error() {
      // Lazily initializes the field defaults
      if (!_classInitialized) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (!_classInitialized) {
            _virtualMachineDefault = io.appmetrica.analytics.protobuf.nano.InternalNano.bytesDefaultValue("JVM");
            _classInitialized = true;
          }
        }
      }
      clear();
    }

    public Error clear() {
      throwable = null;
      threads = null;
      buildId = "";
      isOffline = CrashAndroid.OPTIONAL_BOOL_UNDEFINED;
      methodCallStacktrace = CrashAndroid.StackTraceElement.emptyArray();
      message = "";
      type = CrashAndroid.Error.DEFAULT;
      custom = null;
      virtualMachine = _virtualMachineDefault.clone();
      virtualMachineVersion = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      pluginEnvironment = CrashAndroid.BytesPair.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.throwable != null) {
        output.writeMessage(1, this.throwable);
      }
      if (this.threads != null) {
        output.writeMessage(2, this.threads);
      }
      if (!this.buildId.equals("")) {
        output.writeString(3, this.buildId);
      }
      if (this.isOffline != CrashAndroid.OPTIONAL_BOOL_UNDEFINED) {
        output.writeInt32(4, this.isOffline);
      }
      if (this.methodCallStacktrace != null && this.methodCallStacktrace.length > 0) {
        for (int i = 0; i < this.methodCallStacktrace.length; i++) {
          CrashAndroid.StackTraceElement element = this.methodCallStacktrace[i];
          if (element != null) {
            output.writeMessage(5, element);
          }
        }
      }
      if (!this.message.equals("")) {
        output.writeString(6, this.message);
      }
      if (this.type != CrashAndroid.Error.DEFAULT) {
        output.writeInt32(7, this.type);
      }
      if (this.custom != null) {
        output.writeMessage(8, this.custom);
      }
      if (!java.util.Arrays.equals(this.virtualMachine, _virtualMachineDefault)) {
        output.writeBytes(9, this.virtualMachine);
      }
      if (!java.util.Arrays.equals(this.virtualMachineVersion, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(10, this.virtualMachineVersion);
      }
      if (this.pluginEnvironment != null && this.pluginEnvironment.length > 0) {
        for (int i = 0; i < this.pluginEnvironment.length; i++) {
          CrashAndroid.BytesPair element = this.pluginEnvironment[i];
          if (element != null) {
            output.writeMessage(11, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.throwable != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.throwable);
      }
      if (this.threads != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.threads);
      }
      if (!this.buildId.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.buildId);
      }
      if (this.isOffline != CrashAndroid.OPTIONAL_BOOL_UNDEFINED) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(4, this.isOffline);
      }
      if (this.methodCallStacktrace != null && this.methodCallStacktrace.length > 0) {
        for (int i = 0; i < this.methodCallStacktrace.length; i++) {
          CrashAndroid.StackTraceElement element = this.methodCallStacktrace[i];
          if (element != null) {
            size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(5, element);
          }
        }
      }
      if (!this.message.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.message);
      }
      if (this.type != CrashAndroid.Error.DEFAULT) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(7, this.type);
      }
      if (this.custom != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(8, this.custom);
      }
      if (!java.util.Arrays.equals(this.virtualMachine, _virtualMachineDefault)) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(9, this.virtualMachine);
      }
      if (!java.util.Arrays.equals(this.virtualMachineVersion, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(10, this.virtualMachineVersion);
      }
      if (this.pluginEnvironment != null && this.pluginEnvironment.length > 0) {
        for (int i = 0; i < this.pluginEnvironment.length; i++) {
          CrashAndroid.BytesPair element = this.pluginEnvironment[i];
          if (element != null) {
            size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(11, element);
          }
        }
      }
      return size;
    }

    @Override
    public Error mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.throwable == null) {
              this.throwable = new CrashAndroid.Throwable();
            }
            input.readMessage(this.throwable);
            break;
          }
          case 18: {
            if (this.threads == null) {
              this.threads = new CrashAndroid.AllThreads();
            }
            input.readMessage(this.threads);
            break;
          }
          case 26: {
            this.buildId = input.readString();
            break;
          }
          case 32: {
            int value = input.readInt32();
            switch (value) {
              case CrashAndroid.OPTIONAL_BOOL_UNDEFINED:
              case CrashAndroid.OPTIONAL_BOOL_FALSE:
              case CrashAndroid.OPTIONAL_BOOL_TRUE:
                this.isOffline = value;
                break;
            }
            break;
          }
          case 42: {
            int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 42);
            int i = this.methodCallStacktrace == null ? 0 : this.methodCallStacktrace.length;
            CrashAndroid.StackTraceElement[] newArray =
                new CrashAndroid.StackTraceElement[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.methodCallStacktrace, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new CrashAndroid.StackTraceElement();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new CrashAndroid.StackTraceElement();
            input.readMessage(newArray[i]);
            this.methodCallStacktrace = newArray;
            break;
          }
          case 50: {
            this.message = input.readString();
            break;
          }
          case 56: {
            int value = input.readInt32();
            switch (value) {
              case CrashAndroid.Error.DEFAULT:
              case CrashAndroid.Error.CUSTOM:
                this.type = value;
                break;
            }
            break;
          }
          case 66: {
            if (this.custom == null) {
              this.custom = new CrashAndroid.Error.Custom();
            }
            input.readMessage(this.custom);
            break;
          }
          case 74: {
            this.virtualMachine = input.readBytes();
            break;
          }
          case 82: {
            this.virtualMachineVersion = input.readBytes();
            break;
          }
          case 90: {
            int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 90);
            int i = this.pluginEnvironment == null ? 0 : this.pluginEnvironment.length;
            CrashAndroid.BytesPair[] newArray =
                new CrashAndroid.BytesPair[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.pluginEnvironment, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new CrashAndroid.BytesPair();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new CrashAndroid.BytesPair();
            input.readMessage(newArray[i]);
            this.pluginEnvironment = newArray;
            break;
          }
        }
      }
    }

    public static Error parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Error(), data);
    }

    public static Error parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Error().mergeFrom(input);
    }
  }
}
