// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.appmetrica.analytics.impl.protobuf.backend;

@SuppressWarnings("hiding")
public interface Ecommerce {

  public static final class ECommerceEvent extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    // enum ECommerceEventType
    public static final int ECOMMERCE_EVENT_TYPE_UNDEFINED = 0;
    public static final int ECOMMERCE_EVENT_TYPE_SHOW_SCREEN = 1;
    public static final int ECOMMERCE_EVENT_TYPE_SHOW_PRODUCT_CARD = 2;
    public static final int ECOMMERCE_EVENT_TYPE_SHOW_PRODUCT_DETAILS = 3;
    public static final int ECOMMERCE_EVENT_TYPE_ADD_TO_CART = 4;
    public static final int ECOMMERCE_EVENT_TYPE_REMOVE_FROM_CART = 5;
    public static final int ECOMMERCE_EVENT_TYPE_BEGIN_CHECKOUT = 6;
    public static final int ECOMMERCE_EVENT_TYPE_PURCHASE = 7;

    public static final class Category extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile Category[] _emptyArray;
      public static Category[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Category[0];
            }
          }
        }
        return _emptyArray;
      }

      // repeated bytes path = 1;
      public byte[][] path;

      public Category() {
        clear();
      }

      public Category clear() {
        path = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES_ARRAY;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.path != null && this.path.length > 0) {
          for (int i = 0; i < this.path.length; i++) {
            byte[] element = this.path[i];
            if (element != null) {
              output.writeBytes(1, element);
            }
          }
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.path != null && this.path.length > 0) {
          int dataCount = 0;
          int dataSize = 0;
          for (int i = 0; i < this.path.length; i++) {
            byte[] element = this.path[i];
            if (element != null) {
              dataCount++;
              dataSize += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
                  .computeBytesSizeNoTag(element);
            }
          }
          size += dataSize;
          size += 1 * dataCount;
        }
        return size;
      }

      @Override
      public Category mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 10);
              int i = this.path == null ? 0 : this.path.length;
              byte[][] newArray = new byte[i + arrayLength][];
              if (i != 0) {
                java.lang.System.arraycopy(this.path, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = input.readBytes();
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = input.readBytes();
              this.path = newArray;
              break;
            }
          }
        }
      }

      public static Category parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Category(), data);
      }

      public static Category parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Category().mergeFrom(input);
      }
    }

    public static final class Payload extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      public static final class Pair extends
          io.appmetrica.analytics.protobuf.nano.MessageNano {

        private static volatile Pair[] _emptyArray;
        public static Pair[] emptyArray() {
          // Lazily initializes the empty array
          if (_emptyArray == null) {
            synchronized (
                io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
              if (_emptyArray == null) {
                _emptyArray = new Pair[0];
              }
            }
          }
          return _emptyArray;
        }

        // optional bytes key = 1;
        public byte[] key;

        // optional bytes value = 2;
        public byte[] value;

        public Pair() {
          clear();
        }

        public Pair clear() {
          key = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
          value = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
          cachedSize = -1;
          return this;
        }

        @Override
        public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
            throws java.io.IOException {
          if (!java.util.Arrays.equals(this.key, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
            output.writeBytes(1, this.key);
          }
          if (!java.util.Arrays.equals(this.value, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
            output.writeBytes(2, this.value);
          }
          super.writeTo(output);
        }

        @Override
        protected int computeSerializedSize() {
          int size = super.computeSerializedSize();
          if (!java.util.Arrays.equals(this.key, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
            size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
                .computeBytesSize(1, this.key);
          }
          if (!java.util.Arrays.equals(this.value, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
            size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
                .computeBytesSize(2, this.value);
          }
          return size;
        }

        @Override
        public Pair mergeFrom(
                io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
            throws java.io.IOException {
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                return this;
              default: {
                if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                  return this;
                }
                break;
              }
              case 10: {
                this.key = input.readBytes();
                break;
              }
              case 18: {
                this.value = input.readBytes();
                break;
              }
            }
          }
        }

        public static Pair parseFrom(byte[] data)
            throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
          return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Pair(), data);
        }

        public static Pair parseFrom(
                io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
            throws java.io.IOException {
          return new Pair().mergeFrom(input);
        }
      }

      private static volatile Payload[] _emptyArray;
      public static Payload[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Payload[0];
            }
          }
        }
        return _emptyArray;
      }

      // repeated .ECommerceEvent.Payload.Pair pairs = 1;
      public Ecommerce.ECommerceEvent.Payload.Pair[] pairs;

      // optional uint32 truncated_pairs_count = 2 [default = 0];
      public int truncatedPairsCount;

      public Payload() {
        clear();
      }

      public Payload clear() {
        pairs = Ecommerce.ECommerceEvent.Payload.Pair.emptyArray();
        truncatedPairsCount = 0;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.pairs != null && this.pairs.length > 0) {
          for (int i = 0; i < this.pairs.length; i++) {
            Ecommerce.ECommerceEvent.Payload.Pair element = this.pairs[i];
            if (element != null) {
              output.writeMessage(1, element);
            }
          }
        }
        if (this.truncatedPairsCount != 0) {
          output.writeUInt32(2, this.truncatedPairsCount);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.pairs != null && this.pairs.length > 0) {
          for (int i = 0; i < this.pairs.length; i++) {
            Ecommerce.ECommerceEvent.Payload.Pair element = this.pairs[i];
            if (element != null) {
              size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
                .computeMessageSize(1, element);
            }
          }
        }
        if (this.truncatedPairsCount != 0) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeUInt32Size(2, this.truncatedPairsCount);
        }
        return size;
      }

      @Override
      public Payload mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 10);
              int i = this.pairs == null ? 0 : this.pairs.length;
              Ecommerce.ECommerceEvent.Payload.Pair[] newArray =
                  new Ecommerce.ECommerceEvent.Payload.Pair[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.pairs, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = new Ecommerce.ECommerceEvent.Payload.Pair();
                input.readMessage(newArray[i]);
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = new Ecommerce.ECommerceEvent.Payload.Pair();
              input.readMessage(newArray[i]);
              this.pairs = newArray;
              break;
            }
            case 16: {
              this.truncatedPairsCount = input.readUInt32();
              break;
            }
          }
        }
      }

      public static Payload parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Payload(), data);
      }

      public static Payload parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Payload().mergeFrom(input);
      }
    }

    public static final class Screen extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile Screen[] _emptyArray;
      public static Screen[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Screen[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional bytes name = 1;
      public byte[] name;

      // optional .ECommerceEvent.Category category = 2;
      public Ecommerce.ECommerceEvent.Category category;

      // optional bytes search_query = 3;
      public byte[] searchQuery;

      // optional .ECommerceEvent.Payload payload = 4;
      public Ecommerce.ECommerceEvent.Payload payload;

      public Screen() {
        clear();
      }

      public Screen clear() {
        name = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
        category = null;
        searchQuery = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
        payload = null;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!java.util.Arrays.equals(this.name, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          output.writeBytes(1, this.name);
        }
        if (this.category != null) {
          output.writeMessage(2, this.category);
        }
        if (!java.util.Arrays.equals(this.searchQuery, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          output.writeBytes(3, this.searchQuery);
        }
        if (this.payload != null) {
          output.writeMessage(4, this.payload);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!java.util.Arrays.equals(this.name, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBytesSize(1, this.name);
        }
        if (this.category != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(2, this.category);
        }
        if (!java.util.Arrays.equals(this.searchQuery, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBytesSize(3, this.searchQuery);
        }
        if (this.payload != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(4, this.payload);
        }
        return size;
      }

      @Override
      public Screen mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.name = input.readBytes();
              break;
            }
            case 18: {
              if (this.category == null) {
                this.category = new Ecommerce.ECommerceEvent.Category();
              }
              input.readMessage(this.category);
              break;
            }
            case 26: {
              this.searchQuery = input.readBytes();
              break;
            }
            case 34: {
              if (this.payload == null) {
                this.payload = new Ecommerce.ECommerceEvent.Payload();
              }
              input.readMessage(this.payload);
              break;
            }
          }
        }
      }

      public static Screen parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Screen(), data);
      }

      public static Screen parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Screen().mergeFrom(input);
      }
    }

    public static final class Decimal extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile Decimal[] _emptyArray;
      public static Decimal[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Decimal[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional int64 mantissa = 1 [default = 0];
      public long mantissa;

      // optional int32 exponent = 2 [default = 0];
      public int exponent;

      public Decimal() {
        clear();
      }

      public Decimal clear() {
        mantissa = 0L;
        exponent = 0;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.mantissa != 0L) {
          output.writeInt64(1, this.mantissa);
        }
        if (this.exponent != 0) {
          output.writeInt32(2, this.exponent);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.mantissa != 0L) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeInt64Size(1, this.mantissa);
        }
        if (this.exponent != 0) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(2, this.exponent);
        }
        return size;
      }

      @Override
      public Decimal mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              this.mantissa = input.readInt64();
              break;
            }
            case 16: {
              this.exponent = input.readInt32();
              break;
            }
          }
        }
      }

      public static Decimal parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Decimal(), data);
      }

      public static Decimal parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Decimal().mergeFrom(input);
      }
    }

    public static final class Amount extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile Amount[] _emptyArray;
      public static Amount[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Amount[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional bytes unit_type = 1;
      public byte[] unitType;

      // optional .ECommerceEvent.Decimal value = 2;
      public Ecommerce.ECommerceEvent.Decimal value;

      public Amount() {
        clear();
      }

      public Amount clear() {
        unitType = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
        value = null;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!java.util.Arrays.equals(this.unitType, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          output.writeBytes(1, this.unitType);
        }
        if (this.value != null) {
          output.writeMessage(2, this.value);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!java.util.Arrays.equals(this.unitType, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBytesSize(1, this.unitType);
        }
        if (this.value != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(2, this.value);
        }
        return size;
      }

      @Override
      public Amount mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.unitType = input.readBytes();
              break;
            }
            case 18: {
              if (this.value == null) {
                this.value = new Ecommerce.ECommerceEvent.Decimal();
              }
              input.readMessage(this.value);
              break;
            }
          }
        }
      }

      public static Amount parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Amount(), data);
      }

      public static Amount parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Amount().mergeFrom(input);
      }
    }

    public static final class Price extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile Price[] _emptyArray;
      public static Price[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Price[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional .ECommerceEvent.Amount fiat = 1;
      public Ecommerce.ECommerceEvent.Amount fiat;

      // repeated .ECommerceEvent.Amount internal_components = 2;
      public Ecommerce.ECommerceEvent.Amount[] internalComponents;

      public Price() {
        clear();
      }

      public Price clear() {
        fiat = null;
        internalComponents = Ecommerce.ECommerceEvent.Amount.emptyArray();
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.fiat != null) {
          output.writeMessage(1, this.fiat);
        }
        if (this.internalComponents != null && this.internalComponents.length > 0) {
          for (int i = 0; i < this.internalComponents.length; i++) {
            Ecommerce.ECommerceEvent.Amount element = this.internalComponents[i];
            if (element != null) {
              output.writeMessage(2, element);
            }
          }
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.fiat != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(1, this.fiat);
        }
        if (this.internalComponents != null && this.internalComponents.length > 0) {
          for (int i = 0; i < this.internalComponents.length; i++) {
            Ecommerce.ECommerceEvent.Amount element = this.internalComponents[i];
            if (element != null) {
              size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
                .computeMessageSize(2, element);
            }
          }
        }
        return size;
      }

      @Override
      public Price mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              if (this.fiat == null) {
                this.fiat = new Ecommerce.ECommerceEvent.Amount();
              }
              input.readMessage(this.fiat);
              break;
            }
            case 18: {
              int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 18);
              int i = this.internalComponents == null ? 0 : this.internalComponents.length;
              Ecommerce.ECommerceEvent.Amount[] newArray =
                  new Ecommerce.ECommerceEvent.Amount[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.internalComponents, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = new Ecommerce.ECommerceEvent.Amount();
                input.readMessage(newArray[i]);
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = new Ecommerce.ECommerceEvent.Amount();
              input.readMessage(newArray[i]);
              this.internalComponents = newArray;
              break;
            }
          }
        }
      }

      public static Price parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Price(), data);
      }

      public static Price parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Price().mergeFrom(input);
      }
    }

    public static final class PromoCode extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile PromoCode[] _emptyArray;
      public static PromoCode[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new PromoCode[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional bytes code = 1;
      public byte[] code;

      public PromoCode() {
        clear();
      }

      public PromoCode clear() {
        code = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!java.util.Arrays.equals(this.code, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          output.writeBytes(1, this.code);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!java.util.Arrays.equals(this.code, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBytesSize(1, this.code);
        }
        return size;
      }

      @Override
      public PromoCode mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.code = input.readBytes();
              break;
            }
          }
        }
      }

      public static PromoCode parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new PromoCode(), data);
      }

      public static PromoCode parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new PromoCode().mergeFrom(input);
      }
    }

    public static final class Product extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile Product[] _emptyArray;
      public static Product[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Product[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional bytes sku = 1;
      public byte[] sku;

      // optional bytes name = 2;
      public byte[] name;

      // optional .ECommerceEvent.Category category = 3;
      public Ecommerce.ECommerceEvent.Category category;

      // optional .ECommerceEvent.Payload payload = 4;
      public Ecommerce.ECommerceEvent.Payload payload;

      // optional .ECommerceEvent.Price actual_price = 5;
      public Ecommerce.ECommerceEvent.Price actualPrice;

      // optional .ECommerceEvent.Price original_price = 6;
      public Ecommerce.ECommerceEvent.Price originalPrice;

      // repeated .ECommerceEvent.PromoCode promo_codes = 7;
      public Ecommerce.ECommerceEvent.PromoCode[] promoCodes;

      public Product() {
        clear();
      }

      public Product clear() {
        sku = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
        name = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
        category = null;
        payload = null;
        actualPrice = null;
        originalPrice = null;
        promoCodes = Ecommerce.ECommerceEvent.PromoCode.emptyArray();
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!java.util.Arrays.equals(this.sku, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          output.writeBytes(1, this.sku);
        }
        if (!java.util.Arrays.equals(this.name, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          output.writeBytes(2, this.name);
        }
        if (this.category != null) {
          output.writeMessage(3, this.category);
        }
        if (this.payload != null) {
          output.writeMessage(4, this.payload);
        }
        if (this.actualPrice != null) {
          output.writeMessage(5, this.actualPrice);
        }
        if (this.originalPrice != null) {
          output.writeMessage(6, this.originalPrice);
        }
        if (this.promoCodes != null && this.promoCodes.length > 0) {
          for (int i = 0; i < this.promoCodes.length; i++) {
            Ecommerce.ECommerceEvent.PromoCode element = this.promoCodes[i];
            if (element != null) {
              output.writeMessage(7, element);
            }
          }
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!java.util.Arrays.equals(this.sku, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBytesSize(1, this.sku);
        }
        if (!java.util.Arrays.equals(this.name, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBytesSize(2, this.name);
        }
        if (this.category != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(3, this.category);
        }
        if (this.payload != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(4, this.payload);
        }
        if (this.actualPrice != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(5, this.actualPrice);
        }
        if (this.originalPrice != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(6, this.originalPrice);
        }
        if (this.promoCodes != null && this.promoCodes.length > 0) {
          for (int i = 0; i < this.promoCodes.length; i++) {
            Ecommerce.ECommerceEvent.PromoCode element = this.promoCodes[i];
            if (element != null) {
              size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
                .computeMessageSize(7, element);
            }
          }
        }
        return size;
      }

      @Override
      public Product mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.sku = input.readBytes();
              break;
            }
            case 18: {
              this.name = input.readBytes();
              break;
            }
            case 26: {
              if (this.category == null) {
                this.category = new Ecommerce.ECommerceEvent.Category();
              }
              input.readMessage(this.category);
              break;
            }
            case 34: {
              if (this.payload == null) {
                this.payload = new Ecommerce.ECommerceEvent.Payload();
              }
              input.readMessage(this.payload);
              break;
            }
            case 42: {
              if (this.actualPrice == null) {
                this.actualPrice = new Ecommerce.ECommerceEvent.Price();
              }
              input.readMessage(this.actualPrice);
              break;
            }
            case 50: {
              if (this.originalPrice == null) {
                this.originalPrice = new Ecommerce.ECommerceEvent.Price();
              }
              input.readMessage(this.originalPrice);
              break;
            }
            case 58: {
              int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 58);
              int i = this.promoCodes == null ? 0 : this.promoCodes.length;
              Ecommerce.ECommerceEvent.PromoCode[] newArray =
                  new Ecommerce.ECommerceEvent.PromoCode[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.promoCodes, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = new Ecommerce.ECommerceEvent.PromoCode();
                input.readMessage(newArray[i]);
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = new Ecommerce.ECommerceEvent.PromoCode();
              input.readMessage(newArray[i]);
              this.promoCodes = newArray;
              break;
            }
          }
        }
      }

      public static Product parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Product(), data);
      }

      public static Product parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Product().mergeFrom(input);
      }
    }

    public static final class Referrer extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile Referrer[] _emptyArray;
      public static Referrer[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Referrer[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional bytes type = 1;
      public byte[] type;

      // optional bytes id = 2;
      public byte[] id;

      // optional .ECommerceEvent.Screen screen = 3;
      public Ecommerce.ECommerceEvent.Screen screen;

      public Referrer() {
        clear();
      }

      public Referrer clear() {
        type = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
        id = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
        screen = null;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!java.util.Arrays.equals(this.type, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          output.writeBytes(1, this.type);
        }
        if (!java.util.Arrays.equals(this.id, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          output.writeBytes(2, this.id);
        }
        if (this.screen != null) {
          output.writeMessage(3, this.screen);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!java.util.Arrays.equals(this.type, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBytesSize(1, this.type);
        }
        if (!java.util.Arrays.equals(this.id, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBytesSize(2, this.id);
        }
        if (this.screen != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(3, this.screen);
        }
        return size;
      }

      @Override
      public Referrer mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.type = input.readBytes();
              break;
            }
            case 18: {
              this.id = input.readBytes();
              break;
            }
            case 26: {
              if (this.screen == null) {
                this.screen = new Ecommerce.ECommerceEvent.Screen();
              }
              input.readMessage(this.screen);
              break;
            }
          }
        }
      }

      public static Referrer parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Referrer(), data);
      }

      public static Referrer parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Referrer().mergeFrom(input);
      }
    }

    public static final class CartItem extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile CartItem[] _emptyArray;
      public static CartItem[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new CartItem[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional .ECommerceEvent.Product product = 1;
      public Ecommerce.ECommerceEvent.Product product;

      // optional .ECommerceEvent.Referrer referrer = 2;
      public Ecommerce.ECommerceEvent.Referrer referrer;

      // optional .ECommerceEvent.Decimal quantity = 3;
      public Ecommerce.ECommerceEvent.Decimal quantity;

      // optional .ECommerceEvent.Price revenue = 4;
      public Ecommerce.ECommerceEvent.Price revenue;

      public CartItem() {
        clear();
      }

      public CartItem clear() {
        product = null;
        referrer = null;
        quantity = null;
        revenue = null;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.product != null) {
          output.writeMessage(1, this.product);
        }
        if (this.referrer != null) {
          output.writeMessage(2, this.referrer);
        }
        if (this.quantity != null) {
          output.writeMessage(3, this.quantity);
        }
        if (this.revenue != null) {
          output.writeMessage(4, this.revenue);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.product != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(1, this.product);
        }
        if (this.referrer != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(2, this.referrer);
        }
        if (this.quantity != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(3, this.quantity);
        }
        if (this.revenue != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(4, this.revenue);
        }
        return size;
      }

      @Override
      public CartItem mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              if (this.product == null) {
                this.product = new Ecommerce.ECommerceEvent.Product();
              }
              input.readMessage(this.product);
              break;
            }
            case 18: {
              if (this.referrer == null) {
                this.referrer = new Ecommerce.ECommerceEvent.Referrer();
              }
              input.readMessage(this.referrer);
              break;
            }
            case 26: {
              if (this.quantity == null) {
                this.quantity = new Ecommerce.ECommerceEvent.Decimal();
              }
              input.readMessage(this.quantity);
              break;
            }
            case 34: {
              if (this.revenue == null) {
                this.revenue = new Ecommerce.ECommerceEvent.Price();
              }
              input.readMessage(this.revenue);
              break;
            }
          }
        }
      }

      public static CartItem parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new CartItem(), data);
      }

      public static CartItem parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new CartItem().mergeFrom(input);
      }
    }

    public static final class OrderCartItem extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile OrderCartItem[] _emptyArray;
      public static OrderCartItem[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new OrderCartItem[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional uint32 number_in_cart = 1 [default = 0];
      public int numberInCart;

      // optional .ECommerceEvent.CartItem item = 2;
      public Ecommerce.ECommerceEvent.CartItem item;

      public OrderCartItem() {
        clear();
      }

      public OrderCartItem clear() {
        numberInCart = 0;
        item = null;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.numberInCart != 0) {
          output.writeUInt32(1, this.numberInCart);
        }
        if (this.item != null) {
          output.writeMessage(2, this.item);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.numberInCart != 0) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeUInt32Size(1, this.numberInCart);
        }
        if (this.item != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(2, this.item);
        }
        return size;
      }

      @Override
      public OrderCartItem mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              this.numberInCart = input.readUInt32();
              break;
            }
            case 18: {
              if (this.item == null) {
                this.item = new Ecommerce.ECommerceEvent.CartItem();
              }
              input.readMessage(this.item);
              break;
            }
          }
        }
      }

      public static OrderCartItem parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new OrderCartItem(), data);
      }

      public static OrderCartItem parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new OrderCartItem().mergeFrom(input);
      }
    }

    public static final class Order extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile Order[] _emptyArray;
      public static Order[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Order[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional bytes uuid = 1;
      public byte[] uuid;

      // optional bytes order_id = 2;
      public byte[] orderId;

      // optional .ECommerceEvent.Payload payload = 3;
      public Ecommerce.ECommerceEvent.Payload payload;

      // repeated .ECommerceEvent.OrderCartItem items = 4;
      public Ecommerce.ECommerceEvent.OrderCartItem[] items;

      // optional uint32 total_items_count = 5 [default = 0];
      public int totalItemsCount;

      public Order() {
        clear();
      }

      public Order clear() {
        uuid = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
        orderId = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
        payload = null;
        items = Ecommerce.ECommerceEvent.OrderCartItem.emptyArray();
        totalItemsCount = 0;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!java.util.Arrays.equals(this.uuid, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          output.writeBytes(1, this.uuid);
        }
        if (!java.util.Arrays.equals(this.orderId, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          output.writeBytes(2, this.orderId);
        }
        if (this.payload != null) {
          output.writeMessage(3, this.payload);
        }
        if (this.items != null && this.items.length > 0) {
          for (int i = 0; i < this.items.length; i++) {
            Ecommerce.ECommerceEvent.OrderCartItem element = this.items[i];
            if (element != null) {
              output.writeMessage(4, element);
            }
          }
        }
        if (this.totalItemsCount != 0) {
          output.writeUInt32(5, this.totalItemsCount);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!java.util.Arrays.equals(this.uuid, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBytesSize(1, this.uuid);
        }
        if (!java.util.Arrays.equals(this.orderId, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBytesSize(2, this.orderId);
        }
        if (this.payload != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(3, this.payload);
        }
        if (this.items != null && this.items.length > 0) {
          for (int i = 0; i < this.items.length; i++) {
            Ecommerce.ECommerceEvent.OrderCartItem element = this.items[i];
            if (element != null) {
              size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
                .computeMessageSize(4, element);
            }
          }
        }
        if (this.totalItemsCount != 0) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeUInt32Size(5, this.totalItemsCount);
        }
        return size;
      }

      @Override
      public Order mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.uuid = input.readBytes();
              break;
            }
            case 18: {
              this.orderId = input.readBytes();
              break;
            }
            case 26: {
              if (this.payload == null) {
                this.payload = new Ecommerce.ECommerceEvent.Payload();
              }
              input.readMessage(this.payload);
              break;
            }
            case 34: {
              int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 34);
              int i = this.items == null ? 0 : this.items.length;
              Ecommerce.ECommerceEvent.OrderCartItem[] newArray =
                  new Ecommerce.ECommerceEvent.OrderCartItem[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.items, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = new Ecommerce.ECommerceEvent.OrderCartItem();
                input.readMessage(newArray[i]);
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = new Ecommerce.ECommerceEvent.OrderCartItem();
              input.readMessage(newArray[i]);
              this.items = newArray;
              break;
            }
            case 40: {
              this.totalItemsCount = input.readUInt32();
              break;
            }
          }
        }
      }

      public static Order parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Order(), data);
      }

      public static Order parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Order().mergeFrom(input);
      }
    }

    public static final class ShownScreenInfo extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile ShownScreenInfo[] _emptyArray;
      public static ShownScreenInfo[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new ShownScreenInfo[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional .ECommerceEvent.Screen screen = 1;
      public Ecommerce.ECommerceEvent.Screen screen;

      public ShownScreenInfo() {
        clear();
      }

      public ShownScreenInfo clear() {
        screen = null;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.screen != null) {
          output.writeMessage(1, this.screen);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.screen != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(1, this.screen);
        }
        return size;
      }

      @Override
      public ShownScreenInfo mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              if (this.screen == null) {
                this.screen = new Ecommerce.ECommerceEvent.Screen();
              }
              input.readMessage(this.screen);
              break;
            }
          }
        }
      }

      public static ShownScreenInfo parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new ShownScreenInfo(), data);
      }

      public static ShownScreenInfo parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new ShownScreenInfo().mergeFrom(input);
      }
    }

    public static final class ShownProductCardInfo extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile ShownProductCardInfo[] _emptyArray;
      public static ShownProductCardInfo[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new ShownProductCardInfo[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional .ECommerceEvent.Product product = 1;
      public Ecommerce.ECommerceEvent.Product product;

      // optional .ECommerceEvent.Screen screen = 2;
      public Ecommerce.ECommerceEvent.Screen screen;

      public ShownProductCardInfo() {
        clear();
      }

      public ShownProductCardInfo clear() {
        product = null;
        screen = null;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.product != null) {
          output.writeMessage(1, this.product);
        }
        if (this.screen != null) {
          output.writeMessage(2, this.screen);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.product != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(1, this.product);
        }
        if (this.screen != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(2, this.screen);
        }
        return size;
      }

      @Override
      public ShownProductCardInfo mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              if (this.product == null) {
                this.product = new Ecommerce.ECommerceEvent.Product();
              }
              input.readMessage(this.product);
              break;
            }
            case 18: {
              if (this.screen == null) {
                this.screen = new Ecommerce.ECommerceEvent.Screen();
              }
              input.readMessage(this.screen);
              break;
            }
          }
        }
      }

      public static ShownProductCardInfo parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new ShownProductCardInfo(), data);
      }

      public static ShownProductCardInfo parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new ShownProductCardInfo().mergeFrom(input);
      }
    }

    public static final class ShownProductDetailsInfo extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile ShownProductDetailsInfo[] _emptyArray;
      public static ShownProductDetailsInfo[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new ShownProductDetailsInfo[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional .ECommerceEvent.Product product = 1;
      public Ecommerce.ECommerceEvent.Product product;

      // optional .ECommerceEvent.Referrer referrer = 2;
      public Ecommerce.ECommerceEvent.Referrer referrer;

      public ShownProductDetailsInfo() {
        clear();
      }

      public ShownProductDetailsInfo clear() {
        product = null;
        referrer = null;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.product != null) {
          output.writeMessage(1, this.product);
        }
        if (this.referrer != null) {
          output.writeMessage(2, this.referrer);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.product != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(1, this.product);
        }
        if (this.referrer != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(2, this.referrer);
        }
        return size;
      }

      @Override
      public ShownProductDetailsInfo mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              if (this.product == null) {
                this.product = new Ecommerce.ECommerceEvent.Product();
              }
              input.readMessage(this.product);
              break;
            }
            case 18: {
              if (this.referrer == null) {
                this.referrer = new Ecommerce.ECommerceEvent.Referrer();
              }
              input.readMessage(this.referrer);
              break;
            }
          }
        }
      }

      public static ShownProductDetailsInfo parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new ShownProductDetailsInfo(), data);
      }

      public static ShownProductDetailsInfo parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new ShownProductDetailsInfo().mergeFrom(input);
      }
    }

    public static final class CartActionInfo extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile CartActionInfo[] _emptyArray;
      public static CartActionInfo[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new CartActionInfo[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional .ECommerceEvent.CartItem item = 1;
      public Ecommerce.ECommerceEvent.CartItem item;

      public CartActionInfo() {
        clear();
      }

      public CartActionInfo clear() {
        item = null;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.item != null) {
          output.writeMessage(1, this.item);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.item != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(1, this.item);
        }
        return size;
      }

      @Override
      public CartActionInfo mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              if (this.item == null) {
                this.item = new Ecommerce.ECommerceEvent.CartItem();
              }
              input.readMessage(this.item);
              break;
            }
          }
        }
      }

      public static CartActionInfo parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new CartActionInfo(), data);
      }

      public static CartActionInfo parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new CartActionInfo().mergeFrom(input);
      }
    }

    public static final class OrderInfo extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile OrderInfo[] _emptyArray;
      public static OrderInfo[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new OrderInfo[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional .ECommerceEvent.Order order = 1;
      public Ecommerce.ECommerceEvent.Order order;

      public OrderInfo() {
        clear();
      }

      public OrderInfo clear() {
        order = null;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.order != null) {
          output.writeMessage(1, this.order);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.order != null) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(1, this.order);
        }
        return size;
      }

      @Override
      public OrderInfo mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              if (this.order == null) {
                this.order = new Ecommerce.ECommerceEvent.Order();
              }
              input.readMessage(this.order);
              break;
            }
          }
        }
      }

      public static OrderInfo parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new OrderInfo(), data);
      }

      public static OrderInfo parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new OrderInfo().mergeFrom(input);
      }
    }

    private static volatile ECommerceEvent[] _emptyArray;
    public static ECommerceEvent[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ECommerceEvent[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .ECommerceEvent.ECommerceEventType type = 1 [default = ECOMMERCE_EVENT_TYPE_UNDEFINED];
    public int type;

    // optional .ECommerceEvent.ShownScreenInfo shown_screen_info = 2;
    public Ecommerce.ECommerceEvent.ShownScreenInfo shownScreenInfo;

    // optional .ECommerceEvent.ShownProductCardInfo shown_product_card_info = 3;
    public Ecommerce.ECommerceEvent.ShownProductCardInfo shownProductCardInfo;

    // optional .ECommerceEvent.ShownProductDetailsInfo shown_product_details_info = 4;
    public Ecommerce.ECommerceEvent.ShownProductDetailsInfo shownProductDetailsInfo;

    // optional .ECommerceEvent.CartActionInfo cart_action_info = 5;
    public Ecommerce.ECommerceEvent.CartActionInfo cartActionInfo;

    // optional .ECommerceEvent.OrderInfo order_info = 6;
    public Ecommerce.ECommerceEvent.OrderInfo orderInfo;

    public ECommerceEvent() {
      clear();
    }

    public ECommerceEvent clear() {
      type = Ecommerce.ECommerceEvent.ECOMMERCE_EVENT_TYPE_UNDEFINED;
      shownScreenInfo = null;
      shownProductCardInfo = null;
      shownProductDetailsInfo = null;
      cartActionInfo = null;
      orderInfo = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.type != Ecommerce.ECommerceEvent.ECOMMERCE_EVENT_TYPE_UNDEFINED) {
        output.writeInt32(1, this.type);
      }
      if (this.shownScreenInfo != null) {
        output.writeMessage(2, this.shownScreenInfo);
      }
      if (this.shownProductCardInfo != null) {
        output.writeMessage(3, this.shownProductCardInfo);
      }
      if (this.shownProductDetailsInfo != null) {
        output.writeMessage(4, this.shownProductDetailsInfo);
      }
      if (this.cartActionInfo != null) {
        output.writeMessage(5, this.cartActionInfo);
      }
      if (this.orderInfo != null) {
        output.writeMessage(6, this.orderInfo);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.type != Ecommerce.ECommerceEvent.ECOMMERCE_EVENT_TYPE_UNDEFINED) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.type);
      }
      if (this.shownScreenInfo != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.shownScreenInfo);
      }
      if (this.shownProductCardInfo != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.shownProductCardInfo);
      }
      if (this.shownProductDetailsInfo != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(4, this.shownProductDetailsInfo);
      }
      if (this.cartActionInfo != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(5, this.cartActionInfo);
      }
      if (this.orderInfo != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(6, this.orderInfo);
      }
      return size;
    }

    @Override
    public ECommerceEvent mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case Ecommerce.ECommerceEvent.ECOMMERCE_EVENT_TYPE_UNDEFINED:
              case Ecommerce.ECommerceEvent.ECOMMERCE_EVENT_TYPE_SHOW_SCREEN:
              case Ecommerce.ECommerceEvent.ECOMMERCE_EVENT_TYPE_SHOW_PRODUCT_CARD:
              case Ecommerce.ECommerceEvent.ECOMMERCE_EVENT_TYPE_SHOW_PRODUCT_DETAILS:
              case Ecommerce.ECommerceEvent.ECOMMERCE_EVENT_TYPE_ADD_TO_CART:
              case Ecommerce.ECommerceEvent.ECOMMERCE_EVENT_TYPE_REMOVE_FROM_CART:
              case Ecommerce.ECommerceEvent.ECOMMERCE_EVENT_TYPE_BEGIN_CHECKOUT:
              case Ecommerce.ECommerceEvent.ECOMMERCE_EVENT_TYPE_PURCHASE:
                this.type = value;
                break;
            }
            break;
          }
          case 18: {
            if (this.shownScreenInfo == null) {
              this.shownScreenInfo = new Ecommerce.ECommerceEvent.ShownScreenInfo();
            }
            input.readMessage(this.shownScreenInfo);
            break;
          }
          case 26: {
            if (this.shownProductCardInfo == null) {
              this.shownProductCardInfo = new Ecommerce.ECommerceEvent.ShownProductCardInfo();
            }
            input.readMessage(this.shownProductCardInfo);
            break;
          }
          case 34: {
            if (this.shownProductDetailsInfo == null) {
              this.shownProductDetailsInfo = new Ecommerce.ECommerceEvent.ShownProductDetailsInfo();
            }
            input.readMessage(this.shownProductDetailsInfo);
            break;
          }
          case 42: {
            if (this.cartActionInfo == null) {
              this.cartActionInfo = new Ecommerce.ECommerceEvent.CartActionInfo();
            }
            input.readMessage(this.cartActionInfo);
            break;
          }
          case 50: {
            if (this.orderInfo == null) {
              this.orderInfo = new Ecommerce.ECommerceEvent.OrderInfo();
            }
            input.readMessage(this.orderInfo);
            break;
          }
        }
      }
    }

    public static ECommerceEvent parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new ECommerceEvent(), data);
    }

    public static ECommerceEvent parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ECommerceEvent().mergeFrom(input);
    }
  }
}
