// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.appmetrica.analytics.impl.protobuf.backend;

@SuppressWarnings("hiding")
public interface EventStart {

  public static final class Value extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile Value[] _emptyArray;
    public static Value[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Value[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bytes buildId = 1;
    public byte[] buildId;

    public Value() {
      clear();
    }

    public Value clear() {
      buildId = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!java.util.Arrays.equals(this.buildId, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(1, this.buildId);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!java.util.Arrays.equals(this.buildId, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.buildId);
      }
      return size;
    }

    @Override
    public Value mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.buildId = input.readBytes();
            break;
          }
        }
      }
    }

    public static Value parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Value(), data);
    }

    public static Value parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Value().mergeFrom(input);
    }
  }
}
