// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.appmetrica.analytics.productflow.impl.protobuf.backend;

@SuppressWarnings("hiding")
public final class ProductFlowEvent extends
    io.appmetrica.analytics.protobuf.nano.MessageNano {

  // enum ProductFlowEventType
  public static final int EVENT_TYPE_UNDEFINED = 0;
  public static final int EVENT_TYPE_OFFER_SHOWN = 1;
  public static final int EVENT_TYPE_FLOW_START = 2;
  public static final int EVENT_TYPE_STEP = 3;
  public static final int EVENT_TYPE_FLOW_RESULT = 4;

  public static final class Payload extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    public static final class Pair extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile Pair[] _emptyArray;
      public static Pair[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Pair[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional bytes key = 1;
      public byte[] key;

      // optional bytes value = 2;
      public byte[] value;

      public Pair() {
        clear();
      }

      public Pair clear() {
        key = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
        value = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!java.util.Arrays.equals(this.key, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          output.writeBytes(1, this.key);
        }
        if (!java.util.Arrays.equals(this.value, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          output.writeBytes(2, this.value);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!java.util.Arrays.equals(this.key, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBytesSize(1, this.key);
        }
        if (!java.util.Arrays.equals(this.value, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBytesSize(2, this.value);
        }
        return size;
      }

      @Override
      public Pair mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.key = input.readBytes();
              break;
            }
            case 18: {
              this.value = input.readBytes();
              break;
            }
          }
        }
      }

      public static Pair parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Pair(), data);
      }

      public static Pair parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Pair().mergeFrom(input);
      }
    }

    private static volatile Payload[] _emptyArray;
    public static Payload[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Payload[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .ProductFlowEvent.Payload.Pair pairs = 1;
    public ProductFlowEvent.Payload.Pair[] pairs;

    // optional uint32 truncated_pairs_count = 2 [default = 0];
    public int truncatedPairsCount;

    public Payload() {
      clear();
    }

    public Payload clear() {
      pairs = ProductFlowEvent.Payload.Pair.emptyArray();
      truncatedPairsCount = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.pairs != null && this.pairs.length > 0) {
        for (int i = 0; i < this.pairs.length; i++) {
          ProductFlowEvent.Payload.Pair element = this.pairs[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      if (this.truncatedPairsCount != 0) {
        output.writeUInt32(2, this.truncatedPairsCount);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.pairs != null && this.pairs.length > 0) {
        for (int i = 0; i < this.pairs.length; i++) {
          ProductFlowEvent.Payload.Pair element = this.pairs[i];
          if (element != null) {
            size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      if (this.truncatedPairsCount != 0) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeUInt32Size(2, this.truncatedPairsCount);
      }
      return size;
    }

    @Override
    public Payload mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.pairs == null ? 0 : this.pairs.length;
            ProductFlowEvent.Payload.Pair[] newArray =
                new ProductFlowEvent.Payload.Pair[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.pairs, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new ProductFlowEvent.Payload.Pair();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new ProductFlowEvent.Payload.Pair();
            input.readMessage(newArray[i]);
            this.pairs = newArray;
            break;
          }
          case 16: {
            this.truncatedPairsCount = input.readUInt32();
            break;
          }
        }
      }
    }

    public static Payload parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Payload(), data);
    }

    public static Payload parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Payload().mergeFrom(input);
    }
  }

  public static final class Amount extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile Amount[] _emptyArray;
    public static Amount[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Amount[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bytes unit = 1;
    public byte[] unit;

    // optional int64 mantissa = 2 [default = 0];
    public long mantissa;

    // optional int32 exponent = 3 [default = 0];
    public int exponent;

    public Amount() {
      clear();
    }

    public Amount clear() {
      unit = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      mantissa = 0L;
      exponent = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!java.util.Arrays.equals(this.unit, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(1, this.unit);
      }
      if (this.mantissa != 0L) {
        output.writeInt64(2, this.mantissa);
      }
      if (this.exponent != 0) {
        output.writeInt32(3, this.exponent);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!java.util.Arrays.equals(this.unit, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.unit);
      }
      if (this.mantissa != 0L) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, this.mantissa);
      }
      if (this.exponent != 0) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.exponent);
      }
      return size;
    }

    @Override
    public Amount mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.unit = input.readBytes();
            break;
          }
          case 16: {
            this.mantissa = input.readInt64();
            break;
          }
          case 24: {
            this.exponent = input.readInt32();
            break;
          }
        }
      }
    }

    public static Amount parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Amount(), data);
    }

    public static Amount parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Amount().mergeFrom(input);
    }
  }

  public static final class Referrer extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile Referrer[] _emptyArray;
    public static Referrer[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Referrer[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bytes type = 1;
    public byte[] type;

    // optional bytes identifier = 2;
    public byte[] identifier;

    // optional bytes screen = 3;
    public byte[] screen;

    public Referrer() {
      clear();
    }

    public Referrer clear() {
      type = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      identifier = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      screen = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!java.util.Arrays.equals(this.type, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(1, this.type);
      }
      if (!java.util.Arrays.equals(this.identifier, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(2, this.identifier);
      }
      if (!java.util.Arrays.equals(this.screen, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(3, this.screen);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!java.util.Arrays.equals(this.type, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.type);
      }
      if (!java.util.Arrays.equals(this.identifier, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(2, this.identifier);
      }
      if (!java.util.Arrays.equals(this.screen, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(3, this.screen);
      }
      return size;
    }

    @Override
    public Referrer mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.type = input.readBytes();
            break;
          }
          case 18: {
            this.identifier = input.readBytes();
            break;
          }
          case 26: {
            this.screen = input.readBytes();
            break;
          }
        }
      }
    }

    public static Referrer parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Referrer(), data);
    }

    public static Referrer parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Referrer().mergeFrom(input);
    }
  }

  public static final class ShownInfo extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile ShownInfo[] _emptyArray;
    public static ShownInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ShownInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bytes offer_type = 1;
    public byte[] offerType;

    // optional bytes benefit_type = 2;
    public byte[] benefitType;

    // optional .ProductFlowEvent.Referrer referrer = 3;
    public ProductFlowEvent.Referrer referrer;

    public ShownInfo() {
      clear();
    }

    public ShownInfo clear() {
      offerType = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      benefitType = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      referrer = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!java.util.Arrays.equals(this.offerType, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(1, this.offerType);
      }
      if (!java.util.Arrays.equals(this.benefitType, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(2, this.benefitType);
      }
      if (this.referrer != null) {
        output.writeMessage(3, this.referrer);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!java.util.Arrays.equals(this.offerType, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.offerType);
      }
      if (!java.util.Arrays.equals(this.benefitType, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(2, this.benefitType);
      }
      if (this.referrer != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.referrer);
      }
      return size;
    }

    @Override
    public ShownInfo mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.offerType = input.readBytes();
            break;
          }
          case 18: {
            this.benefitType = input.readBytes();
            break;
          }
          case 26: {
            if (this.referrer == null) {
              this.referrer = new ProductFlowEvent.Referrer();
            }
            input.readMessage(this.referrer);
            break;
          }
        }
      }
    }

    public static ShownInfo parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new ShownInfo(), data);
    }

    public static ShownInfo parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ShownInfo().mergeFrom(input);
    }
  }

  public static final class StepInfo extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile StepInfo[] _emptyArray;
    public static StepInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new StepInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bytes step_type = 1;
    public byte[] stepType;

    // optional bytes step_option = 2;
    public byte[] stepOption;

    public StepInfo() {
      clear();
    }

    public StepInfo clear() {
      stepType = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      stepOption = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!java.util.Arrays.equals(this.stepType, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(1, this.stepType);
      }
      if (!java.util.Arrays.equals(this.stepOption, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(2, this.stepOption);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!java.util.Arrays.equals(this.stepType, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.stepType);
      }
      if (!java.util.Arrays.equals(this.stepOption, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(2, this.stepOption);
      }
      return size;
    }

    @Override
    public StepInfo mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.stepType = input.readBytes();
            break;
          }
          case 18: {
            this.stepOption = input.readBytes();
            break;
          }
        }
      }
    }

    public static StepInfo parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new StepInfo(), data);
    }

    public static StepInfo parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new StepInfo().mergeFrom(input);
    }
  }

  public static final class ResultInfo extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    // enum Status
    public static final int STATUS_UNDEFINED = 0;
    public static final int STATUS_SUCCESS = 1;
    public static final int STATUS_DECLINED = 2;
    public static final int STATUS_PENDING = 3;
    public static final int STATUS_CANCELLED = 4;
    public static final int STATUS_EXPIRED = 5;
    public static final int STATUS_FAIL = 6;

    private static volatile ResultInfo[] _emptyArray;
    public static ResultInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ResultInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .ProductFlowEvent.ResultInfo.Status status = 1 [default = STATUS_UNDEFINED];
    public int status;

    public ResultInfo() {
      clear();
    }

    public ResultInfo clear() {
      status = ProductFlowEvent.ResultInfo.STATUS_UNDEFINED;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.status != ProductFlowEvent.ResultInfo.STATUS_UNDEFINED) {
        output.writeInt32(1, this.status);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.status != ProductFlowEvent.ResultInfo.STATUS_UNDEFINED) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.status);
      }
      return size;
    }

    @Override
    public ResultInfo mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case ProductFlowEvent.ResultInfo.STATUS_UNDEFINED:
              case ProductFlowEvent.ResultInfo.STATUS_SUCCESS:
              case ProductFlowEvent.ResultInfo.STATUS_DECLINED:
              case ProductFlowEvent.ResultInfo.STATUS_PENDING:
              case ProductFlowEvent.ResultInfo.STATUS_CANCELLED:
              case ProductFlowEvent.ResultInfo.STATUS_EXPIRED:
              case ProductFlowEvent.ResultInfo.STATUS_FAIL:
                this.status = value;
                break;
            }
            break;
          }
        }
      }
    }

    public static ResultInfo parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new ResultInfo(), data);
    }

    public static ResultInfo parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ResultInfo().mergeFrom(input);
    }
  }

  private static volatile ProductFlowEvent[] _emptyArray;
  public static ProductFlowEvent[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new ProductFlowEvent[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional bytes product_offer_id = 1;
  public byte[] productOfferId;

  // optional bytes product_id = 2;
  public byte[] productId;

  // optional .ProductFlowEvent.ProductFlowEventType event_type = 3 [default = EVENT_TYPE_UNDEFINED];
  public int eventType;

  // optional .ProductFlowEvent.ShownInfo shown_info = 4;
  public ProductFlowEvent.ShownInfo shownInfo;

  // optional .ProductFlowEvent.StepInfo step_info = 5;
  public ProductFlowEvent.StepInfo stepInfo;

  // optional .ProductFlowEvent.ResultInfo result_info = 6;
  public ProductFlowEvent.ResultInfo resultInfo;

  // optional .ProductFlowEvent.Amount price = 7;
  public ProductFlowEvent.Amount price;

  // optional .ProductFlowEvent.Payload payload = 8;
  public ProductFlowEvent.Payload payload;

  public ProductFlowEvent() {
    clear();
  }

  public ProductFlowEvent clear() {
    productOfferId = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
    productId = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
    eventType = ProductFlowEvent.EVENT_TYPE_UNDEFINED;
    shownInfo = null;
    stepInfo = null;
    resultInfo = null;
    price = null;
    payload = null;
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (!java.util.Arrays.equals(this.productOfferId, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      output.writeBytes(1, this.productOfferId);
    }
    if (!java.util.Arrays.equals(this.productId, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      output.writeBytes(2, this.productId);
    }
    if (this.eventType != ProductFlowEvent.EVENT_TYPE_UNDEFINED) {
      output.writeInt32(3, this.eventType);
    }
    if (this.shownInfo != null) {
      output.writeMessage(4, this.shownInfo);
    }
    if (this.stepInfo != null) {
      output.writeMessage(5, this.stepInfo);
    }
    if (this.resultInfo != null) {
      output.writeMessage(6, this.resultInfo);
    }
    if (this.price != null) {
      output.writeMessage(7, this.price);
    }
    if (this.payload != null) {
      output.writeMessage(8, this.payload);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (!java.util.Arrays.equals(this.productOfferId, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeBytesSize(1, this.productOfferId);
    }
    if (!java.util.Arrays.equals(this.productId, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeBytesSize(2, this.productId);
    }
    if (this.eventType != ProductFlowEvent.EVENT_TYPE_UNDEFINED) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
        .computeInt32Size(3, this.eventType);
    }
    if (this.shownInfo != null) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
        .computeMessageSize(4, this.shownInfo);
    }
    if (this.stepInfo != null) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
        .computeMessageSize(5, this.stepInfo);
    }
    if (this.resultInfo != null) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
        .computeMessageSize(6, this.resultInfo);
    }
    if (this.price != null) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
        .computeMessageSize(7, this.price);
    }
    if (this.payload != null) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
        .computeMessageSize(8, this.payload);
    }
    return size;
  }

  @Override
  public ProductFlowEvent mergeFrom(
          io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 10: {
          this.productOfferId = input.readBytes();
          break;
        }
        case 18: {
          this.productId = input.readBytes();
          break;
        }
        case 24: {
          int value = input.readInt32();
          switch (value) {
            case ProductFlowEvent.EVENT_TYPE_UNDEFINED:
            case ProductFlowEvent.EVENT_TYPE_OFFER_SHOWN:
            case ProductFlowEvent.EVENT_TYPE_FLOW_START:
            case ProductFlowEvent.EVENT_TYPE_STEP:
            case ProductFlowEvent.EVENT_TYPE_FLOW_RESULT:
              this.eventType = value;
              break;
          }
          break;
        }
        case 34: {
          if (this.shownInfo == null) {
            this.shownInfo = new ProductFlowEvent.ShownInfo();
          }
          input.readMessage(this.shownInfo);
          break;
        }
        case 42: {
          if (this.stepInfo == null) {
            this.stepInfo = new ProductFlowEvent.StepInfo();
          }
          input.readMessage(this.stepInfo);
          break;
        }
        case 50: {
          if (this.resultInfo == null) {
            this.resultInfo = new ProductFlowEvent.ResultInfo();
          }
          input.readMessage(this.resultInfo);
          break;
        }
        case 58: {
          if (this.price == null) {
            this.price = new ProductFlowEvent.Amount();
          }
          input.readMessage(this.price);
          break;
        }
        case 66: {
          if (this.payload == null) {
            this.payload = new ProductFlowEvent.Payload();
          }
          input.readMessage(this.payload);
          break;
        }
      }
    }
  }

  public static ProductFlowEvent parseFrom(byte[] data)
      throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
    return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new ProductFlowEvent(), data);
  }

  public static ProductFlowEvent parseFrom(
          io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new ProductFlowEvent().mergeFrom(input);
  }
}
