// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.appmetrica.analytics.impl.protobuf.client;

@SuppressWarnings("hiding")
public interface DbProto {

  public static final class Utils extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    // enum OptionalBool
    public static final int OPTIONAL_BOOL_UNDEFINED = -1;
    public static final int OPTIONAL_BOOL_FALSE = 0;
    public static final int OPTIONAL_BOOL_TRUE = 1;

    private static volatile Utils[] _emptyArray;
    public static Utils[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Utils[0];
          }
        }
      }
      return _emptyArray;
    }

    public Utils() {
      clear();
    }

    public Utils clear() {
      cachedSize = -1;
      return this;
    }

    @Override
    public Utils mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
        }
      }
    }

    public static Utils parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Utils(), data);
    }

    public static Utils parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Utils().mergeFrom(input);
    }
  }

  public static final class Location extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile Location[] _emptyArray;
    public static Location[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Location[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .Utils.OptionalBool enabled = 1 [default = OPTIONAL_BOOL_UNDEFINED];
    public int enabled;

    // optional double longitude = 2 [default = -1];
    public double longitude;

    // optional double latitude = 3 [default = -1];
    public double latitude;

    // optional int32 altitude = 4 [default = -1];
    public int altitude;

    // optional int32 direction = 5 [default = -1];
    public int direction;

    // optional int32 precision = 6 [default = -1];
    public int precision;

    // optional int32 speed = 7 [default = -1];
    public int speed;

    // optional int64 timestamp = 8 [default = -1];
    public long timestamp;

    // optional string provider = 9 [default = ""];
    public java.lang.String provider;

    // optional string originalProvider = 10 [default = ""];
    public java.lang.String originalProvider;

    public Location() {
      clear();
    }

    public Location clear() {
      enabled = DbProto.Utils.OPTIONAL_BOOL_UNDEFINED;
      longitude = -1D;
      latitude = -1D;
      altitude = -1;
      direction = -1;
      precision = -1;
      speed = -1;
      timestamp = -1L;
      provider = "";
      originalProvider = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.enabled != DbProto.Utils.OPTIONAL_BOOL_UNDEFINED) {
        output.writeInt32(1, this.enabled);
      }
      if (java.lang.Double.doubleToLongBits(this.longitude)
          != java.lang.Double.doubleToLongBits(-1D)) {
        output.writeDouble(2, this.longitude);
      }
      if (java.lang.Double.doubleToLongBits(this.latitude)
          != java.lang.Double.doubleToLongBits(-1D)) {
        output.writeDouble(3, this.latitude);
      }
      if (this.altitude != -1) {
        output.writeInt32(4, this.altitude);
      }
      if (this.direction != -1) {
        output.writeInt32(5, this.direction);
      }
      if (this.precision != -1) {
        output.writeInt32(6, this.precision);
      }
      if (this.speed != -1) {
        output.writeInt32(7, this.speed);
      }
      if (this.timestamp != -1L) {
        output.writeInt64(8, this.timestamp);
      }
      if (!this.provider.equals("")) {
        output.writeString(9, this.provider);
      }
      if (!this.originalProvider.equals("")) {
        output.writeString(10, this.originalProvider);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.enabled != DbProto.Utils.OPTIONAL_BOOL_UNDEFINED) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.enabled);
      }
      if (java.lang.Double.doubleToLongBits(this.longitude)
          != java.lang.Double.doubleToLongBits(-1D)) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(2, this.longitude);
      }
      if (java.lang.Double.doubleToLongBits(this.latitude)
          != java.lang.Double.doubleToLongBits(-1D)) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeDoubleSize(3, this.latitude);
      }
      if (this.altitude != -1) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.altitude);
      }
      if (this.direction != -1) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.direction);
      }
      if (this.precision != -1) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(6, this.precision);
      }
      if (this.speed != -1) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(7, this.speed);
      }
      if (this.timestamp != -1L) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(8, this.timestamp);
      }
      if (!this.provider.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(9, this.provider);
      }
      if (!this.originalProvider.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(10, this.originalProvider);
      }
      return size;
    }

    @Override
    public Location mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int value = input.readInt32();
            switch (value) {
              case DbProto.Utils.OPTIONAL_BOOL_UNDEFINED:
              case DbProto.Utils.OPTIONAL_BOOL_FALSE:
              case DbProto.Utils.OPTIONAL_BOOL_TRUE:
                this.enabled = value;
                break;
            }
            break;
          }
          case 17: {
            this.longitude = input.readDouble();
            break;
          }
          case 25: {
            this.latitude = input.readDouble();
            break;
          }
          case 32: {
            this.altitude = input.readInt32();
            break;
          }
          case 40: {
            this.direction = input.readInt32();
            break;
          }
          case 48: {
            this.precision = input.readInt32();
            break;
          }
          case 56: {
            this.speed = input.readInt32();
            break;
          }
          case 64: {
            this.timestamp = input.readInt64();
            break;
          }
          case 74: {
            this.provider = input.readString();
            break;
          }
          case 82: {
            this.originalProvider = input.readString();
            break;
          }
        }
      }
    }

    public static Location parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Location(), data);
    }

    public static Location parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Location().mergeFrom(input);
    }
  }

  public static final class SessionDescription extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile SessionDescription[] _emptyArray;
    public static SessionDescription[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SessionDescription[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 start_time = 1 [default = -1];
    public long startTime;

    // optional int64 server_time_offset = 2 [default = -1];
    public long serverTimeOffset;

    // optional .Utils.OptionalBool obtained_before_first_synchronization = 3 [default = OPTIONAL_BOOL_UNDEFINED];
    public int obtainedBeforeFirstSynchronization;

    public SessionDescription() {
      clear();
    }

    public SessionDescription clear() {
      startTime = -1L;
      serverTimeOffset = -1L;
      obtainedBeforeFirstSynchronization = DbProto.Utils.OPTIONAL_BOOL_UNDEFINED;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.startTime != -1L) {
        output.writeInt64(1, this.startTime);
      }
      if (this.serverTimeOffset != -1L) {
        output.writeInt64(2, this.serverTimeOffset);
      }
      if (this.obtainedBeforeFirstSynchronization != DbProto.Utils.OPTIONAL_BOOL_UNDEFINED) {
        output.writeInt32(3, this.obtainedBeforeFirstSynchronization);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.startTime != -1L) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.startTime);
      }
      if (this.serverTimeOffset != -1L) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(2, this.serverTimeOffset);
      }
      if (this.obtainedBeforeFirstSynchronization != DbProto.Utils.OPTIONAL_BOOL_UNDEFINED) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(3, this.obtainedBeforeFirstSynchronization);
      }
      return size;
    }

    @Override
    public SessionDescription mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.startTime = input.readInt64();
            break;
          }
          case 16: {
            this.serverTimeOffset = input.readInt64();
            break;
          }
          case 24: {
            int value = input.readInt32();
            switch (value) {
              case DbProto.Utils.OPTIONAL_BOOL_UNDEFINED:
              case DbProto.Utils.OPTIONAL_BOOL_FALSE:
              case DbProto.Utils.OPTIONAL_BOOL_TRUE:
                this.obtainedBeforeFirstSynchronization = value;
                break;
            }
            break;
          }
        }
      }
    }

    public static SessionDescription parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new SessionDescription(), data);
    }

    public static SessionDescription parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SessionDescription().mergeFrom(input);
    }
  }

  public static final class EventDescription extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    private static volatile EventDescription[] _emptyArray;
    public static EventDescription[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new EventDescription[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 custom_type = 1 [default = -1];
    public int customType;

    // optional string name = 2 [default = ""];
    public java.lang.String name;

    // optional string value = 3 [default = ""];
    public java.lang.String value;

    // optional int64 number_of_type = 4 [default = -1];
    public long numberOfType;

    // optional .Location location_info = 5;
    public DbProto.Location locationInfo;

    // optional string error_environment = 6 [default = ""];
    public java.lang.String errorEnvironment;

    // optional string app_environment = 7 [default = ""];
    public java.lang.String appEnvironment;

    // optional int64 app_environment_revision = 8 [default = -1];
    public long appEnvironmentRevision;

    // optional int32 truncated = 9 [default = -1];
    public int truncated;

    // optional int32 connection_type = 10 [default = -1];
    public int connectionType;

    // optional string cellular_connection_type = 11 [default = ""];
    public java.lang.String cellularConnectionType;

    // optional int32 encrypting_mode = 12 [default = -1];
    public int encryptingMode;

    // optional string profile_id = 13 [default = ""];
    public java.lang.String profileId;

    // optional int32 first_occurrence_status = 14 [default = -1];
    public int firstOccurrenceStatus;

    // optional int32 source = 15 [default = -1];
    public int source;

    // optional .Utils.OptionalBool attribution_id_changed = 16 [default = OPTIONAL_BOOL_UNDEFINED];
    public int attributionIdChanged;

    // optional int32 open_id = 17 [default = -1];
    public int openId;

    // optional bytes extras = 18 [default = ""];
    public byte[] extras;

    public EventDescription() {
      clear();
    }

    public EventDescription clear() {
      customType = -1;
      name = "";
      value = "";
      numberOfType = -1L;
      locationInfo = null;
      errorEnvironment = "";
      appEnvironment = "";
      appEnvironmentRevision = -1L;
      truncated = -1;
      connectionType = -1;
      cellularConnectionType = "";
      encryptingMode = -1;
      profileId = "";
      firstOccurrenceStatus = -1;
      source = -1;
      attributionIdChanged = DbProto.Utils.OPTIONAL_BOOL_UNDEFINED;
      openId = -1;
      extras = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.customType != -1) {
        output.writeInt32(1, this.customType);
      }
      if (!this.name.equals("")) {
        output.writeString(2, this.name);
      }
      if (!this.value.equals("")) {
        output.writeString(3, this.value);
      }
      if (this.numberOfType != -1L) {
        output.writeInt64(4, this.numberOfType);
      }
      if (this.locationInfo != null) {
        output.writeMessage(5, this.locationInfo);
      }
      if (!this.errorEnvironment.equals("")) {
        output.writeString(6, this.errorEnvironment);
      }
      if (!this.appEnvironment.equals("")) {
        output.writeString(7, this.appEnvironment);
      }
      if (this.appEnvironmentRevision != -1L) {
        output.writeInt64(8, this.appEnvironmentRevision);
      }
      if (this.truncated != -1) {
        output.writeInt32(9, this.truncated);
      }
      if (this.connectionType != -1) {
        output.writeInt32(10, this.connectionType);
      }
      if (!this.cellularConnectionType.equals("")) {
        output.writeString(11, this.cellularConnectionType);
      }
      if (this.encryptingMode != -1) {
        output.writeInt32(12, this.encryptingMode);
      }
      if (!this.profileId.equals("")) {
        output.writeString(13, this.profileId);
      }
      if (this.firstOccurrenceStatus != -1) {
        output.writeInt32(14, this.firstOccurrenceStatus);
      }
      if (this.source != -1) {
        output.writeInt32(15, this.source);
      }
      if (this.attributionIdChanged != DbProto.Utils.OPTIONAL_BOOL_UNDEFINED) {
        output.writeInt32(16, this.attributionIdChanged);
      }
      if (this.openId != -1) {
        output.writeInt32(17, this.openId);
      }
      if (!java.util.Arrays.equals(this.extras, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(18, this.extras);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.customType != -1) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.customType);
      }
      if (!this.name.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.name);
      }
      if (!this.value.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.value);
      }
      if (this.numberOfType != -1L) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(4, this.numberOfType);
      }
      if (this.locationInfo != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(5, this.locationInfo);
      }
      if (!this.errorEnvironment.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.errorEnvironment);
      }
      if (!this.appEnvironment.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.appEnvironment);
      }
      if (this.appEnvironmentRevision != -1L) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(8, this.appEnvironmentRevision);
      }
      if (this.truncated != -1) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(9, this.truncated);
      }
      if (this.connectionType != -1) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(10, this.connectionType);
      }
      if (!this.cellularConnectionType.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(11, this.cellularConnectionType);
      }
      if (this.encryptingMode != -1) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(12, this.encryptingMode);
      }
      if (!this.profileId.equals("")) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(13, this.profileId);
      }
      if (this.firstOccurrenceStatus != -1) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(14, this.firstOccurrenceStatus);
      }
      if (this.source != -1) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(15, this.source);
      }
      if (this.attributionIdChanged != DbProto.Utils.OPTIONAL_BOOL_UNDEFINED) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(16, this.attributionIdChanged);
      }
      if (this.openId != -1) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(17, this.openId);
      }
      if (!java.util.Arrays.equals(this.extras, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(18, this.extras);
      }
      return size;
    }

    @Override
    public EventDescription mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.customType = input.readInt32();
            break;
          }
          case 18: {
            this.name = input.readString();
            break;
          }
          case 26: {
            this.value = input.readString();
            break;
          }
          case 32: {
            this.numberOfType = input.readInt64();
            break;
          }
          case 42: {
            if (this.locationInfo == null) {
              this.locationInfo = new DbProto.Location();
            }
            input.readMessage(this.locationInfo);
            break;
          }
          case 50: {
            this.errorEnvironment = input.readString();
            break;
          }
          case 58: {
            this.appEnvironment = input.readString();
            break;
          }
          case 64: {
            this.appEnvironmentRevision = input.readInt64();
            break;
          }
          case 72: {
            this.truncated = input.readInt32();
            break;
          }
          case 80: {
            this.connectionType = input.readInt32();
            break;
          }
          case 90: {
            this.cellularConnectionType = input.readString();
            break;
          }
          case 96: {
            this.encryptingMode = input.readInt32();
            break;
          }
          case 106: {
            this.profileId = input.readString();
            break;
          }
          case 112: {
            this.firstOccurrenceStatus = input.readInt32();
            break;
          }
          case 120: {
            this.source = input.readInt32();
            break;
          }
          case 128: {
            int value = input.readInt32();
            switch (value) {
              case DbProto.Utils.OPTIONAL_BOOL_UNDEFINED:
              case DbProto.Utils.OPTIONAL_BOOL_FALSE:
              case DbProto.Utils.OPTIONAL_BOOL_TRUE:
                this.attributionIdChanged = value;
                break;
            }
            break;
          }
          case 136: {
            this.openId = input.readInt32();
            break;
          }
          case 146: {
            this.extras = input.readBytes();
            break;
          }
        }
      }
    }

    public static EventDescription parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new EventDescription(), data);
    }

    public static EventDescription parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new EventDescription().mergeFrom(input);
    }
  }
}
