// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.appmetrica.analytics.impl.protobuf.client;

@SuppressWarnings("hiding")
public interface EventExtrasProto {

  public static final class EventExtras extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    public static final class ExtrasEntry extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile ExtrasEntry[] _emptyArray;
      public static ExtrasEntry[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new ExtrasEntry[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional string key = 1;
      public java.lang.String key;

      // optional bytes value = 2;
      public byte[] value;

      public ExtrasEntry() {
        clear();
      }

      public ExtrasEntry clear() {
        key = "";
        value = io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!this.key.equals("")) {
          output.writeString(1, this.key);
        }
        if (!java.util.Arrays.equals(this.value, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          output.writeBytes(2, this.value);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!this.key.equals("")) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, this.key);
        }
        if (!java.util.Arrays.equals(this.value, io.appmetrica.analytics.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBytesSize(2, this.value);
        }
        return size;
      }

      @Override
      public ExtrasEntry mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.key = input.readString();
              break;
            }
            case 18: {
              this.value = input.readBytes();
              break;
            }
          }
        }
      }

      public static ExtrasEntry parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new ExtrasEntry(), data);
      }

      public static ExtrasEntry parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new ExtrasEntry().mergeFrom(input);
      }
    }

    private static volatile EventExtras[] _emptyArray;
    public static EventExtras[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new EventExtras[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .EventExtras.ExtrasEntry extras = 1;
    public EventExtrasProto.EventExtras.ExtrasEntry[] extras;

    public EventExtras() {
      clear();
    }

    public EventExtras clear() {
      extras = EventExtrasProto.EventExtras.ExtrasEntry.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.extras != null && this.extras.length > 0) {
        for (int i = 0; i < this.extras.length; i++) {
          EventExtrasProto.EventExtras.ExtrasEntry element = this.extras[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.extras != null && this.extras.length > 0) {
        for (int i = 0; i < this.extras.length; i++) {
          EventExtrasProto.EventExtras.ExtrasEntry element = this.extras[i];
          if (element != null) {
            size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public EventExtras mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.extras == null ? 0 : this.extras.length;
            EventExtrasProto.EventExtras.ExtrasEntry[] newArray =
                new EventExtrasProto.EventExtras.ExtrasEntry[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.extras, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new EventExtrasProto.EventExtras.ExtrasEntry();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new EventExtrasProto.EventExtras.ExtrasEntry();
            input.readMessage(newArray[i]);
            this.extras = newArray;
            break;
          }
        }
      }
    }

    public static EventExtras parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new EventExtras(), data);
    }

    public static EventExtras parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new EventExtras().mergeFrom(input);
    }
  }
}
