// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.appmetrica.analytics.impl.protobuf.client;

@SuppressWarnings("hiding")
public interface PreloadInfoProto {

  public static final class PreloadInfoData extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    // enum Source
    public static final int UNDEFINED = 0;
    public static final int APP = 1;
    public static final int RETAIL = 2;
    public static final int SATELLITE = 3;

    public static final class PreloadInfoCandidate extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile PreloadInfoCandidate[] _emptyArray;
      public static PreloadInfoCandidate[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new PreloadInfoCandidate[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional string trackingId = 1;
      public java.lang.String trackingId;

      // optional string additionalParameters = 2 [default = ""];
      public java.lang.String additionalParameters;

      // required .PreloadInfoData.Source source = 3 [default = UNDEFINED];
      public int source;

      public PreloadInfoCandidate() {
        clear();
      }

      public PreloadInfoCandidate clear() {
        trackingId = "";
        additionalParameters = "";
        source = PreloadInfoProto.PreloadInfoData.UNDEFINED;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!this.trackingId.equals("")) {
          output.writeString(1, this.trackingId);
        }
        if (!this.additionalParameters.equals("")) {
          output.writeString(2, this.additionalParameters);
        }
        output.writeInt32(3, this.source);
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!this.trackingId.equals("")) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, this.trackingId);
        }
        if (!this.additionalParameters.equals("")) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(2, this.additionalParameters);
        }
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(3, this.source);
        return size;
      }

      @Override
      public PreloadInfoCandidate mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.trackingId = input.readString();
              break;
            }
            case 18: {
              this.additionalParameters = input.readString();
              break;
            }
            case 24: {
              int value = input.readInt32();
              switch (value) {
                case PreloadInfoProto.PreloadInfoData.UNDEFINED:
                case PreloadInfoProto.PreloadInfoData.APP:
                case PreloadInfoProto.PreloadInfoData.RETAIL:
                case PreloadInfoProto.PreloadInfoData.SATELLITE:
                  this.source = value;
                  break;
              }
              break;
            }
          }
        }
      }

      public static PreloadInfoCandidate parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new PreloadInfoCandidate(), data);
      }

      public static PreloadInfoCandidate parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new PreloadInfoCandidate().mergeFrom(input);
      }
    }

    public static final class PreloadInfo extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      private static volatile PreloadInfo[] _emptyArray;
      public static PreloadInfo[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new PreloadInfo[0];
            }
          }
        }
        return _emptyArray;
      }

      // optional string trackingId = 1;
      public java.lang.String trackingId;

      // optional string additionalParameters = 2 [default = ""];
      public java.lang.String additionalParameters;

      // optional bool wasSet = 3 [default = false];
      public boolean wasSet;

      // optional bool preloadInfoAutoTracking = 4 [default = false];
      public boolean preloadInfoAutoTracking;

      // required .PreloadInfoData.Source source = 5 [default = UNDEFINED];
      public int source;

      public PreloadInfo() {
        clear();
      }

      public PreloadInfo clear() {
        trackingId = "";
        additionalParameters = "";
        wasSet = false;
        preloadInfoAutoTracking = false;
        source = PreloadInfoProto.PreloadInfoData.UNDEFINED;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (!this.trackingId.equals("")) {
          output.writeString(1, this.trackingId);
        }
        if (!this.additionalParameters.equals("")) {
          output.writeString(2, this.additionalParameters);
        }
        if (this.wasSet != false) {
          output.writeBool(3, this.wasSet);
        }
        if (this.preloadInfoAutoTracking != false) {
          output.writeBool(4, this.preloadInfoAutoTracking);
        }
        output.writeInt32(5, this.source);
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (!this.trackingId.equals("")) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, this.trackingId);
        }
        if (!this.additionalParameters.equals("")) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(2, this.additionalParameters);
        }
        if (this.wasSet != false) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBoolSize(3, this.wasSet);
        }
        if (this.preloadInfoAutoTracking != false) {
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeBoolSize(4, this.preloadInfoAutoTracking);
        }
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(5, this.source);
        return size;
      }

      @Override
      public PreloadInfo mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.trackingId = input.readString();
              break;
            }
            case 18: {
              this.additionalParameters = input.readString();
              break;
            }
            case 24: {
              this.wasSet = input.readBool();
              break;
            }
            case 32: {
              this.preloadInfoAutoTracking = input.readBool();
              break;
            }
            case 40: {
              int value = input.readInt32();
              switch (value) {
                case PreloadInfoProto.PreloadInfoData.UNDEFINED:
                case PreloadInfoProto.PreloadInfoData.APP:
                case PreloadInfoProto.PreloadInfoData.RETAIL:
                case PreloadInfoProto.PreloadInfoData.SATELLITE:
                  this.source = value;
                  break;
              }
              break;
            }
          }
        }
      }

      public static PreloadInfo parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new PreloadInfo(), data);
      }

      public static PreloadInfo parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new PreloadInfo().mergeFrom(input);
      }
    }

    private static volatile PreloadInfoData[] _emptyArray;
    public static PreloadInfoData[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PreloadInfoData[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .PreloadInfoData.PreloadInfo chosenPreloadInfo = 1;
    public PreloadInfoProto.PreloadInfoData.PreloadInfo chosenPreloadInfo;

    // repeated .PreloadInfoData.PreloadInfoCandidate candidates = 2;
    public PreloadInfoProto.PreloadInfoData.PreloadInfoCandidate[] candidates;

    public PreloadInfoData() {
      clear();
    }

    public PreloadInfoData clear() {
      chosenPreloadInfo = null;
      candidates = PreloadInfoProto.PreloadInfoData.PreloadInfoCandidate.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.chosenPreloadInfo != null) {
        output.writeMessage(1, this.chosenPreloadInfo);
      }
      if (this.candidates != null && this.candidates.length > 0) {
        for (int i = 0; i < this.candidates.length; i++) {
          PreloadInfoProto.PreloadInfoData.PreloadInfoCandidate element = this.candidates[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.chosenPreloadInfo != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.chosenPreloadInfo);
      }
      if (this.candidates != null && this.candidates.length > 0) {
        for (int i = 0; i < this.candidates.length; i++) {
          PreloadInfoProto.PreloadInfoData.PreloadInfoCandidate element = this.candidates[i];
          if (element != null) {
            size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      return size;
    }

    @Override
    public PreloadInfoData mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.chosenPreloadInfo == null) {
              this.chosenPreloadInfo = new PreloadInfoProto.PreloadInfoData.PreloadInfo();
            }
            input.readMessage(this.chosenPreloadInfo);
            break;
          }
          case 18: {
            int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.candidates == null ? 0 : this.candidates.length;
            PreloadInfoProto.PreloadInfoData.PreloadInfoCandidate[] newArray =
                new PreloadInfoProto.PreloadInfoData.PreloadInfoCandidate[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.candidates, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new PreloadInfoProto.PreloadInfoData.PreloadInfoCandidate();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new PreloadInfoProto.PreloadInfoData.PreloadInfoCandidate();
            input.readMessage(newArray[i]);
            this.candidates = newArray;
            break;
          }
        }
      }
    }

    public static PreloadInfoData parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new PreloadInfoData(), data);
    }

    public static PreloadInfoData parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PreloadInfoData().mergeFrom(input);
    }
  }
}
