// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.appmetrica.analytics.impl.protobuf.client;

@SuppressWarnings("hiding")
public final class ReferrerInfoClient extends
    io.appmetrica.analytics.protobuf.nano.MessageNano {

  // enum Source
  public static final int UNKNOWN = 0;
  public static final int GP = 1;
  public static final int HMS = 2;

  private static volatile ReferrerInfoClient[] _emptyArray;
  public static ReferrerInfoClient[] emptyArray() {
    // Lazily initializes the empty array
    if (_emptyArray == null) {
      synchronized (
          io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
        if (_emptyArray == null) {
          _emptyArray = new ReferrerInfoClient[0];
        }
      }
    }
    return _emptyArray;
  }

  // optional string value = 1;
  public java.lang.String value;

  // optional uint64 installBeginTimeSeconds = 2;
  public long installBeginTimeSeconds;

  // optional uint64 clickTimeSeconds = 3;
  public long clickTimeSeconds;

  // optional .ReferrerInfoClient.Source source = 4 [default = UNKNOWN];
  public int source;

  public ReferrerInfoClient() {
    clear();
  }

  public ReferrerInfoClient clear() {
    value = "";
    installBeginTimeSeconds = 0L;
    clickTimeSeconds = 0L;
    source = ReferrerInfoClient.UNKNOWN;
    cachedSize = -1;
    return this;
  }

  @Override
  public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
      throws java.io.IOException {
    if (!this.value.equals("")) {
      output.writeString(1, this.value);
    }
    if (this.installBeginTimeSeconds != 0L) {
      output.writeUInt64(2, this.installBeginTimeSeconds);
    }
    if (this.clickTimeSeconds != 0L) {
      output.writeUInt64(3, this.clickTimeSeconds);
    }
    if (this.source != ReferrerInfoClient.UNKNOWN) {
      output.writeInt32(4, this.source);
    }
    super.writeTo(output);
  }

  @Override
  protected int computeSerializedSize() {
    int size = super.computeSerializedSize();
    if (!this.value.equals("")) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.value);
    }
    if (this.installBeginTimeSeconds != 0L) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(2, this.installBeginTimeSeconds);
    }
    if (this.clickTimeSeconds != 0L) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeUInt64Size(3, this.clickTimeSeconds);
    }
    if (this.source != ReferrerInfoClient.UNKNOWN) {
      size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
        .computeInt32Size(4, this.source);
    }
    return size;
  }

  @Override
  public ReferrerInfoClient mergeFrom(
          io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    while (true) {
      int tag = input.readTag();
      switch (tag) {
        case 0:
          return this;
        default: {
          if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
            return this;
          }
          break;
        }
        case 10: {
          this.value = input.readString();
          break;
        }
        case 16: {
          this.installBeginTimeSeconds = input.readUInt64();
          break;
        }
        case 24: {
          this.clickTimeSeconds = input.readUInt64();
          break;
        }
        case 32: {
          int value = input.readInt32();
          switch (value) {
            case ReferrerInfoClient.UNKNOWN:
            case ReferrerInfoClient.GP:
            case ReferrerInfoClient.HMS:
              this.source = value;
              break;
          }
          break;
        }
      }
    }
  }

  public static ReferrerInfoClient parseFrom(byte[] data)
      throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
    return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new ReferrerInfoClient(), data);
  }

  public static ReferrerInfoClient parseFrom(
          io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
      throws java.io.IOException {
    return new ReferrerInfoClient().mergeFrom(input);
  }
}
