// Generated by the protocol buffer compiler.  DO NOT EDIT!

package io.appmetrica.analytics.impl.protobuf.client;

@SuppressWarnings("hiding")
public interface SatelliteClidsInfoProto {

  public static final class SatelliteClidsInfo extends
      io.appmetrica.analytics.protobuf.nano.MessageNano {

    public static final class NullableMap extends
        io.appmetrica.analytics.protobuf.nano.MessageNano {

      public static final class Pair extends
          io.appmetrica.analytics.protobuf.nano.MessageNano {

        private static volatile Pair[] _emptyArray;
        public static Pair[] emptyArray() {
          // Lazily initializes the empty array
          if (_emptyArray == null) {
            synchronized (
                io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
              if (_emptyArray == null) {
                _emptyArray = new Pair[0];
              }
            }
          }
          return _emptyArray;
        }

        // required string key = 1;
        public java.lang.String key;

        // optional string value = 2;
        public java.lang.String value;

        public Pair() {
          clear();
        }

        public Pair clear() {
          key = "";
          value = "";
          cachedSize = -1;
          return this;
        }

        @Override
        public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
            throws java.io.IOException {
          output.writeString(1, this.key);
          if (!this.value.equals("")) {
            output.writeString(2, this.value);
          }
          super.writeTo(output);
        }

        @Override
        protected int computeSerializedSize() {
          int size = super.computeSerializedSize();
          size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(1, this.key);
          if (!this.value.equals("")) {
            size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSize(2, this.value);
          }
          return size;
        }

        @Override
        public Pair mergeFrom(
                io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
            throws java.io.IOException {
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                return this;
              default: {
                if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                  return this;
                }
                break;
              }
              case 10: {
                this.key = input.readString();
                break;
              }
              case 18: {
                this.value = input.readString();
                break;
              }
            }
          }
        }

        public static Pair parseFrom(byte[] data)
            throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
          return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new Pair(), data);
        }

        public static Pair parseFrom(
                io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
            throws java.io.IOException {
          return new Pair().mergeFrom(input);
        }
      }

      private static volatile NullableMap[] _emptyArray;
      public static NullableMap[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new NullableMap[0];
            }
          }
        }
        return _emptyArray;
      }

      // repeated .SatelliteClidsInfo.NullableMap.Pair pairs = 1;
      public SatelliteClidsInfoProto.SatelliteClidsInfo.NullableMap.Pair[] pairs;

      public NullableMap() {
        clear();
      }

      public NullableMap clear() {
        pairs = SatelliteClidsInfoProto.SatelliteClidsInfo.NullableMap.Pair.emptyArray();
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.pairs != null && this.pairs.length > 0) {
          for (int i = 0; i < this.pairs.length; i++) {
            SatelliteClidsInfoProto.SatelliteClidsInfo.NullableMap.Pair element = this.pairs[i];
            if (element != null) {
              output.writeMessage(1, element);
            }
          }
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.pairs != null && this.pairs.length > 0) {
          for (int i = 0; i < this.pairs.length; i++) {
            SatelliteClidsInfoProto.SatelliteClidsInfo.NullableMap.Pair element = this.pairs[i];
            if (element != null) {
              size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
                .computeMessageSize(1, element);
            }
          }
        }
        return size;
      }

      @Override
      public NullableMap mergeFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              int arrayLength = io.appmetrica.analytics.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 10);
              int i = this.pairs == null ? 0 : this.pairs.length;
              SatelliteClidsInfoProto.SatelliteClidsInfo.NullableMap.Pair[] newArray =
                  new SatelliteClidsInfoProto.SatelliteClidsInfo.NullableMap.Pair[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.pairs, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = new SatelliteClidsInfoProto.SatelliteClidsInfo.NullableMap.Pair();
                input.readMessage(newArray[i]);
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = new SatelliteClidsInfoProto.SatelliteClidsInfo.NullableMap.Pair();
              input.readMessage(newArray[i]);
              this.pairs = newArray;
              break;
            }
          }
        }
      }

      public static NullableMap parseFrom(byte[] data)
          throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
        return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new NullableMap(), data);
      }

      public static NullableMap parseFrom(
              io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new NullableMap().mergeFrom(input);
      }
    }

    private static volatile SatelliteClidsInfo[] _emptyArray;
    public static SatelliteClidsInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            io.appmetrica.analytics.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SatelliteClidsInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .SatelliteClidsInfo.NullableMap clids = 1;
    public SatelliteClidsInfoProto.SatelliteClidsInfo.NullableMap clids;

    // optional bool checked = 2 [default = false];
    public boolean checked;

    public SatelliteClidsInfo() {
      clear();
    }

    public SatelliteClidsInfo clear() {
      clids = null;
      checked = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.clids != null) {
        output.writeMessage(1, this.clids);
      }
      if (this.checked != false) {
        output.writeBool(2, this.checked);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.clids != null) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.clids);
      }
      if (this.checked != false) {
        size += io.appmetrica.analytics.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(2, this.checked);
      }
      return size;
    }

    @Override
    public SatelliteClidsInfo mergeFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!io.appmetrica.analytics.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.clids == null) {
              this.clids = new SatelliteClidsInfoProto.SatelliteClidsInfo.NullableMap();
            }
            input.readMessage(this.clids);
            break;
          }
          case 16: {
            this.checked = input.readBool();
            break;
          }
        }
      }
    }

    public static SatelliteClidsInfo parseFrom(byte[] data)
        throws io.appmetrica.analytics.protobuf.nano.InvalidProtocolBufferNanoException {
      return io.appmetrica.analytics.protobuf.nano.MessageNano.mergeFrom(new SatelliteClidsInfo(), data);
    }

    public static SatelliteClidsInfo parseFrom(
            io.appmetrica.analytics.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SatelliteClidsInfo().mergeFrom(input);
    }
  }
}
